### Đăng ký tài khoản instructor
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "firstName": "Lực",
  "lastName": "Trần",
  "email": "luc2@gv.com",
  "password": "123456",
  "role": "instructor"
}
