# === GENERAL PATTERNS ===
GENERAL_PATTERNS = [
    r"top\s*\d+",
    r"\d+\s*%",
    r"\d+\s*năm",
    r"thế\s*kỷ\s*\d+",
]
# === TRIẾT HỌC MÁC-LÊNIN / MARXIST-LENINIST PHILOSOPHY ===
PHILOSOPHY_ML_PATTERNS = [
    # Vietnamese
    r"triết\s*học\s*mác", r"chủ\s*nghĩa\s*duy\s*vật", r"chủ\s*nghĩa\s*duy\s*tâm",
    r"biện\s*chứng", r"siêu\s*hình", r"phép\s*biện\s*chứng", r"duy\s*vật\s*biện\s*chứng",
    r"duy\s*vật\s*lịch\s*sử", r"ý\s*thức\s*xã\s*hội", r"tồn\s*tại\s*xã\s*hội",
    r"quy\s*luật\s*mâu\s*thuẫn", r"quy\s*luật\s*lượng\s*chất", r"quy\s*luật\s*phủ\s*định",
    r"thống\s*nhất\s*và\s*đấu\s*tranh", r"mặt\s*đối\s*lập", r"mâu\s*thuẫn\s*biện\s*chứng",
    r"lượng\s*đổi\s*chất\s*đổi", r"bước\s*nhảy", r"phủ\s*định\s*của\s*phủ\s*định",
    r"cái\s*chung", r"cái\s*riêng", r"nguyên\s*nhân", r"kết\s*quả",
    r"tất\s*nhiên", r"ngẫu\s*nhiên", r"nội\s*dung", r"hình\s*thức",
    r"bản\s*chất", r"hiện\s*tượng", r"khả\s*năng", r"hiện\s*thực",
    r"thực\s*tiễn", r"lý\s*luận", r"nhận\s*thức", r"chân\s*lý",
    r"phạm\s*trù", r"khái\s*niệm", r"phản\s*ánh", r"khách\s*quan",
    # English
    r"dialectical\s*materialism", r"historical\s*materialism", r"dialectics",
    r"metaphysics", r"thesis", r"antithesis", r"synthesis",
    r"law\s*of\s*contradiction", r"law\s*of\s*negation", r"quantity\s*quality",
]

# === TƯ TƯỞNG HỒ CHÍ MINH / HO CHI MINH IDEOLOGY ===
HCM_THOUGHT_PATTERNS = [
    r"tư\s*tưởng\s*hồ\s*chí\s*minh", r"bác\s*hồ", r"chủ\s*tịch\s*hồ\s*chí\s*minh",
    r"độc\s*lập\s*dân\s*tộc", r"chủ\s*nghĩa\s*xã\s*hội", r"đại\s*đoàn\s*kết",
    r"dân\s*chủ", r"cần\s*kiệm\s*liêm\s*chính", r"chí\s*công\s*vô\s*tư",
    r"đạo\s*đức\s*cách\s*mạng", r"tự\s*phê\s*bình", r"phê\s*bình",
    r"nhân\s*văn", r"kháng\s*chiến", r"kiến\s*quốc", r"giải\s*phóng\s*dân\s*tộc",
]

# === KINH TẾ CHÍNH TRỊ / POLITICAL ECONOMY ===
POLITICAL_ECONOMY_PATTERNS = [
    r"kinh\s*tế\s*chính\s*trị", r"giá\s*trị\s*thặng\s*dư", r"tư\s*bản",
    r"sức\s*lao\s*động", r"tư\s*liệu\s*sản\s*xuất", r"quan\s*hệ\s*sản\s*xuất",
    r"lực\s*lượng\s*sản\s*xuất", r"phương\s*thức\s*sản\s*xuất",
    r"hàng\s*hóa", r"giá\s*trị\s*sử\s*dụng", r"giá\s*trị\s*trao\s*đổi",
    r"tiền\s*tệ", r"lưu\s*thông\s*tiền\s*tệ", r"tích\s*lũy\s*tư\s*bản",
    r"cấu\s*tạo\s*hữu\s*cơ", r"tỷ\s*suất\s*lợi\s*nhuận", r"địa\s*tô",
    r"kinh\s*tế\s*thị\s*trường", r"kinh\s*tế\s*kế\s*hoạch",
    r"surplus\s*value", r"means\s*of\s*production", r"mode\s*of\s*production",
    r"commodity", r"use\s*value", r"exchange\s*value", r"capital\s*accumulation",
]

# === CHỦ NGHĨA XÃ HỘI KHOA HỌC / SCIENTIFIC SOCIALISM ===
SCIENTIFIC_SOCIALISM_PATTERNS = [
    r"chủ\s*nghĩa\s*xã\s*hội\s*khoa\s*học", r"giai\s*cấp\s*công\s*nhân",
    r"đấu\s*tranh\s*giai\s*cấp", r"cách\s*mạng\s*xã\s*hội", r"nhà\s*nước",
    r"chuyên\s*chính\s*vô\s*sản", r"dân\s*chủ\s*xã\s*hội\s*chủ\s*nghĩa",
    r"liên\s*minh\s*công\s*nông", r"thời\s*kỳ\s*quá\s*độ",
]

# === PHÁP LUẬT ĐẠI CƯƠNG / GENERAL LAW ===
GENERAL_LAW_PATTERNS = [
    # Vietnamese
    r"pháp\s*luật", r"hiến\s*pháp", r"luật", r"bộ\s*luật", r"nghị\s*định",
    r"thông\s*tư", r"quyết\s*định", r"văn\s*bản\s*quy\s*phạm", r"quy\s*phạm\s*pháp\s*luật",
    r"quan\s*hệ\s*pháp\s*luật", r"chủ\s*thể", r"khách\s*thể", r"nội\s*dung",
    r"sự\s*kiện\s*pháp\s*lý", r"vi\s*phạm\s*pháp\s*luật", r"trách\s*nhiệm\s*pháp\s*lý",
    r"hình\s*sự", r"dân\s*sự", r"hành\s*chính", r"kỷ\s*luật",
    r"tội\s*phạm", r"hình\s*phạt", r"bồi\s*thường\s*thiệt\s*hại",
    r"quyền\s*công\s*dân", r"nghĩa\s*vụ\s*công\s*dân", r"quyền\s*con\s*người",
    r"tòa\s*án", r"viện\s*kiểm\s*sát", r"luật\s*sư", r"xét\s*xử",
    # English
    r"constitution", r"legislation", r"statute", r"regulation", r"decree",
    r"legal\s*norm", r"legal\s*relationship", r"legal\s*liability",
    r"criminal\s*law", r"civil\s*law", r"administrative\s*law",
    r"crime", r"punishment", r"compensation", r"human\s*rights",
]

# SQL PATTERNS
SQL_PATTERNS = [
    # DDL
    r"CREATE\s*TABLE", r"ALTER\s*TABLE", r"DROP\s*TABLE", r"TRUNCATE",
    r"CREATE\s*DATABASE", r"CREATE\s*INDEX", r"CREATE\s*VIEW",
    r"PRIMARY\s*KEY", r"FOREIGN\s*KEY", r"UNIQUE", r"NOT\s*NULL", r"DEFAULT",
    r"AUTO_INCREMENT", r"IDENTITY", r"CHECK\s*CONSTRAINT",
    # DML
    r"SELECT", r"INSERT\s*INTO", r"UPDATE", r"DELETE\s*FROM",
    r"WHERE", r"AND", r"OR", r"NOT", r"IN", r"BETWEEN", r"LIKE", r"IS\s*NULL",
    r"ORDER\s*BY", r"GROUP\s*BY", r"HAVING", r"LIMIT", r"OFFSET", r"TOP",
    r"DISTINCT", r"AS", r"ALIAS",
    # Joins
    r"INNER\s*JOIN", r"LEFT\s*JOIN", r"RIGHT\s*JOIN", r"FULL\s*JOIN", r"CROSS\s*JOIN",
    r"SELF\s*JOIN", r"NATURAL\s*JOIN", r"ON", r"USING",
    # Aggregates
    r"COUNT", r"SUM", r"AVG", r"MIN", r"MAX", r"GROUP_CONCAT",
    # Subqueries
    r"SUBQUERY", r"EXISTS", r"ANY", r"ALL", r"UNION", r"UNION\s*ALL",
    r"INTERSECT", r"EXCEPT",
    # Advanced
    r"CASE\s*WHEN", r"COALESCE", r"NULLIF", r"CAST", r"CONVERT",
    r"STORED\s*PROCEDURE", r"FUNCTION", r"TRIGGER", r"VIEW", r"INDEX",
    r"TRANSACTION", r"COMMIT", r"ROLLBACK", r"SAVEPOINT",
    r"GRANT", r"REVOKE", r"BEGIN", r"END",
    # Vietnamese
    r"khóa\s*chính", r"khóa\s*ngoại", r"bảng", r"truy\s*vấn", r"câu\s*lệnh",
    r"ràng\s*buộc", r"chỉ\s*mục", r"giao\s*dịch", r"khóa\s*ngoại",
]

# SOFTWARE ENGINEERING CORE PATTERNS
SE_CORE_PATTERNS = [
    # SDLC
    r"SDLC", r"vòng\s*đời\s*phần\s*mềm", r"software\s*development\s*life\s*cycle",
    r"phân\s*tích\s*yêu\s*cầu", r"thiết\s*kế", r"lập\s*trình", r"kiểm\s*thử", r"bảo\s*trì",
    r"requirements\s*analysis", r"design", r"implementation", r"testing", r"maintenance",
    # Methodologies
    r"waterfall", r"spiral", r"incremental", r"iterative", r"RAD",
    r"agile", r"scrum", r"kanban", r"extreme\s*programming", r"XP",
    r"sprint", r"backlog", r"user\s*story", r"epic", r"velocity",
    r"daily\s*standup", r"retrospective", r"sprint\s*review",
    # Design Patterns
    r"design\s*pattern", r"singleton", r"factory", r"abstract\s*factory",
    r"builder", r"prototype", r"adapter", r"bridge", r"composite",
    r"decorator", r"facade", r"flyweight", r"proxy",
    r"chain\s*of\s*responsibility", r"command", r"interpreter", r"iterator",
    r"mediator", r"memento", r"observer", r"state", r"strategy",
    r"template\s*method", r"visitor",
    # SOLID
    r"SOLID", r"single\s*responsibility", r"open\s*closed", r"liskov",
    r"interface\s*segregation", r"dependency\s*inversion",
    r"nguyên\s*tắc\s*đơn\s*trách\s*nhiệm", r"nguyên\s*tắc\s*đóng\s*mở",
    # UML
    r"UML", r"use\s*case\s*diagram", r"class\s*diagram", r"sequence\s*diagram",
    r"activity\s*diagram", r"state\s*diagram", r"component\s*diagram",
    r"biểu\s*đồ\s*lớp", r"biểu\s*đồ\s*ca\s*sử\s*dụng", r"biểu\s*đồ\s*tuần\s*tự",
    # Testing
    r"unit\s*test", r"integration\s*test", r"system\s*test", r"acceptance\s*test",
    r"regression\s*test", r"smoke\s*test", r"black\s*box", r"white\s*box",
    r"TDD", r"BDD", r"mock", r"stub", r"code\s*coverage",
    # Version Control
    r"git", r"branch", r"merge", r"rebase", r"pull\s*request", r"commit",
    r"repository", r"clone", r"fork", r"conflict\s*resolution",
    # CI/CD
    r"CI/CD", r"continuous\s*integration", r"continuous\s*deployment",
    r"jenkins", r"github\s*actions", r"gitlab\s*ci", r"docker", r"kubernetes",
]

# MATHEMATICS UNIVERSITY PATTERNS
MATH_UNIVERSITY_PATTERNS = [
    # Calculus
    r"giới\s*hạn", r"liên\s*tục", r"đạo\s*hàm", r"vi\s*phân", r"tích\s*phân",
    r"nguyên\s*hàm", r"tích\s*phân\s*xác\s*định", r"tích\s*phân\s*bội",
    r"chuỗi\s*số", r"chuỗi\s*hàm", r"chuỗi\s*lũy\s*thừa", r"chuỗi\s*Fourier",
    r"limit", r"continuity", r"derivative", r"differential", r"integral",
    r"antiderivative", r"definite\s*integral", r"double\s*integral", r"triple\s*integral",
    r"series", r"power\s*series", r"Taylor\s*series", r"Maclaurin\s*series",
    # Linear Algebra
    r"ma\s*trận", r"định\s*thức", r"vector", r"không\s*gian\s*vector",
    r"giá\s*trị\s*riêng", r"vector\s*riêng", r"hạng\s*ma\s*trận",
    r"nghịch\s*đảo\s*ma\s*trận", r"hệ\s*phương\s*trình\s*tuyến\s*tính",
    r"matrix", r"determinant", r"eigenvalue", r"eigenvector", r"rank",
    r"inverse\s*matrix", r"linear\s*system", r"Gaussian\s*elimination",
    # Probability & Statistics
    r"xác\s*suất", r"biến\s*cố", r"phân\s*phối", r"kỳ\s*vọng", r"phương\s*sai",
    r"độ\s*lệch\s*chuẩn", r"phân\s*phối\s*chuẩn", r"phân\s*phối\s*nhị\s*thức",
    r"ước\s*lượng", r"kiểm\s*định\s*giả\s*thuyết", r"khoảng\s*tin\s*cậy",
    r"probability", r"event", r"distribution", r"expected\s*value", r"variance",
    r"standard\s*deviation", r"normal\s*distribution", r"binomial\s*distribution",
    r"hypothesis\s*testing", r"confidence\s*interval", r"p-value",
    # Discrete Math
    r"logic\s*mệnh\s*đề", r"lý\s*thuyết\s*tập\s*hợp", r"quan\s*hệ", r"hàm",
    r"đồ\s*thị", r"cây", r"thuật\s*toán", r"độ\s*phức\s*tạp",
    r"quy\s*nạp", r"đếm", r"hoán\s*vị", r"tổ\s*hợp", r"chỉnh\s*hợp",
    r"propositional\s*logic", r"set\s*theory", r"relation", r"function",
    r"graph\s*theory", r"tree", r"algorithm", r"complexity",
    r"induction", r"counting", r"permutation", r"combination",
]

# === IT - PROGRAMMING ===
IT_PROGRAMMING_PATTERNS = [
    r"thông\s*dịch",
    r"biên\s*dịch",
    r"hướng\s*đối\s*tượng",
    r"lập\s*trình",
    r"ngôn\s*ngữ",
    r"mã\s*nguồn",
    r"open\s*source",
    r"framework",
    r"library",
    r"api",
    r"sdk",
    r"ide",
    r"debug",
    r"compile",
    r"runtime",
    r"syntax",
    r"algorithm",
    r"data\s*structure",
    r"oop",
    r"mvc",
    r"mvvm",
    r"restful",
    r"graphql",
    r"git",
    r"version\s*control",
    r"agile",
    r"scrum",
    r"devops",
    r"ci/cd",
    r"unit\s*test",
    r"integration\s*test",
]

# === IT - DATABASE ===
IT_DATABASE_PATTERNS = [
    r"cơ\s*sở\s*dữ\s*liệu",
    r"database",
    r"sql",
    r"nosql",
    r"mongodb",
    r"mysql",
    r"postgresql",
    r"oracle",
    r"sqlite",
    r"redis",
    r"elasticsearch",
    r"primary\s*key",
    r"foreign\s*key",
    r"index",
    r"query",
    r"select",
    r"insert",
    r"update",
    r"delete",
    r"join",
    r"transaction",
    r"acid",
    r"base",
    r"cap\s*theorem",
    r"normalization",
    r"denormalization",
    r"1nf", r"2nf", r"3nf", r"bcnf",
    r"schema",
    r"table",
    r"record",
    r"field",
    r"stored\s*procedure",
    r"trigger",
    r"view",
    r"cursor",
]

# === IT - NETWORKING ===
IT_NETWORKING_PATTERNS = [
    r"tcp/ip",
    r"tcp",
    r"udp",
    r"http",
    r"https",
    r"ftp",
    r"sftp",
    r"ssh",
    r"telnet",
    r"dns",
    r"dhcp",
    r"nat",
    r"ip\s*address",
    r"ipv4",
    r"ipv6",
    r"subnet",
    r"gateway",
    r"router",
    r"switch",
    r"hub",
    r"bridge",
    r"firewall",
    r"proxy",
    r"vpn",
    r"lan",
    r"wan",
    r"man",
    r"wlan",
    r"wifi",
    r"ethernet",
    r"osi",
    r"protocol",
    r"bandwidth",
    r"latency",
    r"throughput",
    r"packet",
    r"frame",
    r"socket",
    r"port",
]

# === IT - SECURITY ===
IT_SECURITY_PATTERNS = [
    r"bảo\s*mật",
    r"security",
    r"encryption",
    r"decryption",
    r"symmetric",
    r"asymmetric",
    r"aes",
    r"rsa",
    r"hash",
    r"md5",
    r"sha",
    r"sha-256",
    r"sha-512",
    r"ssl",
    r"tls",
    r"certificate",
    r"digital\s*signature",
    r"public\s*key",
    r"private\s*key",
    r"authentication",
    r"authorization",
    r"oauth",
    r"jwt",
    r"session",
    r"cookie",
    r"xss",
    r"sql\s*injection",
    r"csrf",
    r"ddos",
    r"dos",
    r"mitm",
    r"phishing",
    r"malware",
    r"ransomware",
    r"virus",
    r"trojan",
    r"worm",
    r"spyware",
    r"firewall",
    r"ids",
    r"ips",
    r"penetration\s*test",
    r"vulnerability",
]

# === IT - WEB/SOFTWARE ===
IT_WEB_SOFTWARE_PATTERNS = [
    r"frontend",
    r"backend",
    r"fullstack",
    r"responsive",
    r"ui/ux",
    r"ui",
    r"ux",
    r"html",
    r"css",
    r"sass",
    r"less",
    r"javascript",
    r"typescript",
    r"react",
    r"angular",
    r"vue",
    r"svelte",
    r"nextjs",
    r"nuxt",
    r"nodejs",
    r"express",
    r"nestjs",
    r"django",
    r"flask",
    r"fastapi",
    r"spring",
    r"laravel",
    r"rails",
    r"asp\.net",
    r"python",
    r"java",
    r"c\+\+",
    r"c#",
    r"php",
    r"ruby",
    r"go",
    r"rust",
    r"kotlin",
    r"swift",
    r"scala",
    r"docker",
    r"kubernetes",
    r"k8s",
    r"container",
    r"microservice",
    r"monolithic",
    r"serverless",
    r"lambda",
    r"cloud",
    r"aws",
    r"azure",
    r"gcp",
    r"heroku",
    r"vercel",
    r"netlify",
]

# === IT - AI/ML ===
IT_AI_ML_PATTERNS = [
    r"machine\s*learning",
    r"deep\s*learning",
    r"neural\s*network",
    r"artificial\s*intelligence",
    r"ai",
    r"ml",
    r"nlp",
    r"computer\s*vision",
    r"tensorflow",
    r"pytorch",
    r"keras",
    r"scikit-learn",
    r"pandas",
    r"numpy",
    r"supervised",
    r"unsupervised",
    r"reinforcement",
    r"classification",
    r"regression",
    r"clustering",
    r"cnn",
    r"rnn",
    r"lstm",
    r"transformer",
    r"bert",
    r"gpt",
    r"llm",
    r"chatbot",
    r"training",
    r"inference",
    r"model",
    r"dataset",
    r"feature",
    r"label",
    r"accuracy",
    r"precision",
    r"recall",
    r"f1\s*score",
    r"overfitting",
    r"underfitting",
]

# === MATHEMATICS ===
MATH_PATTERNS = [
    r"\^2", r"\^3", r"\^n",
    r"sqrt",
    r"log",
    r"ln",
    r"sin", r"cos", r"tan",
    r"cot", r"sec", r"csc",
    r"arcsin", r"arccos", r"arctan",
    r"pi",
    r"euler",
    # Vietnamese
    r"đạo\s*hàm",
    r"vi\s*phân",
    r"tích\s*phân",
    r"giới\s*hạn",
    r"liên\s*tục",
    r"ma\s*trận",
    r"định\s*thức",
    r"vector",
    r"vô\s*hướng",
    r"hàm\s*số",
    r"đồ\s*thị",
    r"phương\s*trình",
    r"bất\s*phương\s*trình",
    r"hệ\s*phương\s*trình",
    r"hệ\s*số",
    r"nghiệm",
    r"đa\s*thức",
    r"lũy\s*thừa",
    r"căn\s*bậc",
    r"logarit",
    r"số\s*phức",
    r"số\s*thực",
    r"số\s*nguyên",
    r"số\s*hữu\s*tỉ",
    r"số\s*vô\s*tỉ",
    r"xác\s*suất",
    r"thống\s*kê",
    r"trung\s*bình",
    r"phương\s*sai",
    r"độ\s*lệch\s*chuẩn",
    r"phân\s*phối",
    r"chuẩn",
    r"hoán\s*vị",
    r"chỉnh\s*hợp",
    r"tổ\s*hợp",
    r"nhị\s*thức",
    r"cấp\s*số\s*cộng",
    r"cấp\s*số\s*nhân",
    r"dãy\s*số",
    # English equivalents
    r"derivative",
    r"differential",
    r"integral",
    r"limit",
    r"continuous",
    r"discontinuous",
    r"matrix",
    r"matrices",
    r"determinant",
    r"scalar",
    r"function",
    r"graph",
    r"equation",
    r"inequality",
    r"system\s*of\s*equations",
    r"coefficient",
    r"solution",
    r"root",
    r"polynomial",
    r"exponent",
    r"power",
    r"square\s*root",
    r"cube\s*root",
    r"logarithm",
    r"complex\s*number",
    r"real\s*number",
    r"integer",
    r"rational\s*number",
    r"irrational\s*number",
    r"probability",
    r"statistics",
    r"mean",
    r"average",
    r"variance",
    r"standard\s*deviation",
    r"distribution",
    r"normal\s*distribution",
    r"permutation",
    r"combination",
    r"binomial",
    r"arithmetic\s*sequence",
    r"geometric\s*sequence",
    r"sequence",
    r"series",
    r"convergence",
    r"divergence",
    r"asymptote",
    r"domain",
    r"range",
    r"inverse\s*function",
    r"composite\s*function",
]

# === PHYSICS ===
PHYSICS_PATTERNS = [
    r"f\s*=\s*m\s*\*?\s*a",
    r"e\s*=\s*m\s*c\^?2",
    r"v\s*=\s*s/t",
    r"p\s*=\s*m\s*\*?\s*v",
    r"w\s*=\s*f\s*\*?\s*s",
    # Vietnamese
    r"năng\s*lượng",
    r"động\s*năng",
    r"thế\s*năng",
    r"cơ\s*năng",
    r"công",
    r"công\s*suất",
    r"hiệu\s*suất",
    r"điện\s*trở",
    r"điện\s*áp",
    r"hiệu\s*điện\s*thế",
    r"cường\s*độ\s*dòng\s*điện",
    r"từ\s*trường",
    r"điện\s*trường",
    r"cảm\s*ứng",
    r"sóng",
    r"sóng\s*điện\s*từ",
    r"sóng\s*cơ",
    r"tần\s*số",
    r"bước\s*sóng",
    r"chu\s*kỳ",
    r"biên\s*độ",
    r"dao\s*động",
    r"dao\s*động\s*điều\s*hòa",
    r"cộng\s*hưởng",
    r"giao\s*thoa",
    r"nhiễu\s*xạ",
    r"phản\s*xạ",
    r"khúc\s*xạ",
    r"quang\s*học",
    r"thấu\s*kính",
    r"gương",
    r"lăng\s*kính",
    r"nhiệt\s*độ",
    r"nhiệt\s*lượng",
    r"nhiệt\s*dung",
    r"áp\s*suất",
    r"thể\s*tích",
    r"khối\s*lượng\s*riêng",
    r"lực",
    r"lực\s*ma\s*sát",
    r"lực\s*đàn\s*hồi",
    r"lực\s*hấp\s*dẫn",
    r"gia\s*tốc",
    r"vận\s*tốc",
    r"quãng\s*đường",
    r"chuyển\s*động",
    r"chuyển\s*động\s*thẳng",
    r"chuyển\s*động\s*tròn",
    r"quán\s*tính",
    r"động\s*lượng",
    r"xung\s*lượng",
    # English equivalents
    r"energy",
    r"kinetic\s*energy",
    r"potential\s*energy",
    r"mechanical\s*energy",
    r"work",
    r"power",
    r"efficiency",
    r"resistance",
    r"voltage",
    r"potential\s*difference",
    r"current",
    r"electric\s*current",
    r"magnetic\s*field",
    r"electric\s*field",
    r"induction",
    r"electromagnetic\s*induction",
    r"wave",
    r"electromagnetic\s*wave",
    r"mechanical\s*wave",
    r"frequency",
    r"wavelength",
    r"period",
    r"amplitude",
    r"oscillation",
    r"vibration",
    r"harmonic\s*motion",
    r"simple\s*harmonic\s*motion",
    r"resonance",
    r"interference",
    r"diffraction",
    r"reflection",
    r"refraction",
    r"optics",
    r"lens",
    r"mirror",
    r"prism",
    r"temperature",
    r"heat",
    r"heat\s*capacity",
    r"specific\s*heat",
    r"pressure",
    r"volume",
    r"density",
    r"force",
    r"friction",
    r"elastic\s*force",
    r"gravitational\s*force",
    r"gravity",
    r"acceleration",
    r"velocity",
    r"speed",
    r"distance",
    r"displacement",
    r"motion",
    r"linear\s*motion",
    r"circular\s*motion",
    r"inertia",
    r"momentum",
    r"impulse",
    r"newton",
    r"joule",
    r"watt",
    r"ohm",
    r"ampere",
    r"hertz",
]

# === CHEMISTRY ===
CHEMISTRY_PATTERNS = [
    r"h2o", r"co2", r"o2", r"h2", r"n2", r"cl2",
    r"nacl", r"hcl", r"h2so4", r"hno3", r"h3po4",
    r"naoh", r"koh", r"ca\(oh\)2", r"ba\(oh\)2",
    r"caco3", r"na2co3", r"nahco3",
    r"feso4", r"cuso4", r"agno3",
    r"ch4", r"c2h5oh", r"ch3cooh",
    r"c6h12o6", r"c12h22o11",
    r"ph",
    r"mol",
    # Vietnamese
    r"nguyên\s*tử",
    r"phân\s*tử",
    r"ion",
    r"cation",
    r"anion",
    r"electron",
    r"proton",
    r"neutron",
    r"hạt\s*nhân",
    r"lớp\s*vỏ",
    r"orbital",
    r"hóa\s*trị",
    r"số\s*oxi\s*hóa",
    r"liên\s*kết",
    r"liên\s*kết\s*ion",
    r"liên\s*kết\s*cộng\s*hóa\s*trị",
    r"liên\s*kết\s*kim\s*loại",
    r"phản\s*ứng",
    r"phản\s*ứng\s*oxi\s*hóa\s*khử",
    r"phản\s*ứng\s*trao\s*đổi",
    r"oxi\s*hóa",
    r"khử",
    r"chất\s*oxi\s*hóa",
    r"chất\s*khử",
    r"axit",
    r"bazơ",
    r"muối",
    r"oxit",
    r"hidroxit",
    r"dung\s*dịch",
    r"nồng\s*độ",
    r"nồng\s*độ\s*mol",
    r"nồng\s*độ\s*phần\s*trăm",
    r"hữu\s*cơ",
    r"vô\s*cơ",
    r"hiđrocacbon",
    r"ankan", r"anken", r"ankin",
    r"ancol", r"phenol",
    r"anđehit", r"xeton",
    r"axit\s*cacboxylic",
    r"este", r"lipit",
    r"amin", r"amino\s*axit",
    r"polime",
    r"điện\s*phân",
    r"pin\s*điện\s*hóa",
    # English equivalents
    r"atom",
    r"molecule",
    r"nucleus",
    r"shell",
    r"electron\s*shell",
    r"valence",
    r"oxidation\s*state",
    r"oxidation\s*number",
    r"bond",
    r"chemical\s*bond",
    r"ionic\s*bond",
    r"covalent\s*bond",
    r"metallic\s*bond",
    r"reaction",
    r"chemical\s*reaction",
    r"redox",
    r"redox\s*reaction",
    r"oxidation-reduction",
    r"exchange\s*reaction",
    r"oxidation",
    r"reduction",
    r"oxidizing\s*agent",
    r"reducing\s*agent",
    r"acid",
    r"base",
    r"alkali",
    r"salt",
    r"oxide",
    r"hydroxide",
    r"solution",
    r"concentration",
    r"molar\s*concentration",
    r"molarity",
    r"percent\s*concentration",
    r"organic",
    r"inorganic",
    r"hydrocarbon",
    r"alkane", r"alkene", r"alkyne",
    r"alcohol",
    r"aldehyde", r"ketone",
    r"carboxylic\s*acid",
    r"ester", r"lipid", r"fat",
    r"amine", r"amino\s*acid",
    r"polymer",
    r"electrolysis",
    r"electrochemical\s*cell",
    r"galvanic\s*cell",
    r"catalyst",
    r"equilibrium",
    r"stoichiometry",
    r"titration",
    r"precipitate",
    r"soluble",
    r"insoluble",
]

# === BIOLOGY ===
BIOLOGY_PATTERNS = [
    r"dna", r"rna",
    r"adn", r"arn",
    r"nucleotit",
    r"nucleic",
    # Vietnamese
    r"tế\s*bào",
    r"màng\s*tế\s*bào",
    r"nhân\s*tế\s*bào",
    r"ti\s*thể",
    r"lục\s*lạp",
    r"ribosom",
    r"lưới\s*nội\s*chất",
    r"bộ\s*golgi",
    r"lysosom",
    r"không\s*bào",
    r"tế\s*bào\s*chất",
    r"quang\s*hợp",
    r"hô\s*hấp",
    r"hô\s*hấp\s*tế\s*bào",
    r"atp",
    r"adp",
    r"enzyme",
    r"xúc\s*tác",
    r"cơ\s*chất",
    r"di\s*truyền",
    r"gen",
    r"alen",
    r"kiểu\s*gen",
    r"kiểu\s*hình",
    r"nhiễm\s*sắc\s*thể",
    r"nst",
    r"nguyên\s*phân",
    r"giảm\s*phân",
    r"đột\s*biến",
    r"đột\s*biến\s*gen",
    r"đột\s*biến\s*nst",
    r"tiến\s*hóa",
    r"chọn\s*lọc\s*tự\s*nhiên",
    r"thích\s*nghi",
    r"loài",
    r"sinh\s*thái",
    r"quần\s*thể",
    r"quần\s*xã",
    r"hệ\s*sinh\s*thái",
    r"chuỗi\s*thức\s*ăn",
    r"lưới\s*thức\s*ăn",
    r"sinh\s*vật\s*sản\s*xuất",
    r"sinh\s*vật\s*tiêu\s*thụ",
    r"sinh\s*vật\s*phân\s*giải",
    r"protein",
    r"lipit",
    r"gluxit",
    r"cacbohidrat",
    r"vitamin",
    r"hormone",
    r"kháng\s*thể",
    r"kháng\s*nguyên",
    r"miễn\s*dịch",
    # English equivalents
    r"cell",
    r"cell\s*membrane",
    r"plasma\s*membrane",
    r"nucleus",
    r"cell\s*nucleus",
    r"mitochondria",
    r"mitochondrion",
    r"chloroplast",
    r"ribosome",
    r"endoplasmic\s*reticulum",
    r"golgi\s*apparatus",
    r"golgi\s*body",
    r"lysosome",
    r"vacuole",
    r"cytoplasm",
    r"photosynthesis",
    r"respiration",
    r"cellular\s*respiration",
    r"adenosine\s*triphosphate",
    r"adenosine\s*diphosphate",
    r"catalyst",
    r"substrate",
    r"genetics",
    r"heredity",
    r"gene",
    r"allele",
    r"genotype",
    r"phenotype",
    r"chromosome",
    r"mitosis",
    r"meiosis",
    r"cell\s*division",
    r"mutation",
    r"gene\s*mutation",
    r"chromosomal\s*mutation",
    r"evolution",
    r"natural\s*selection",
    r"adaptation",
    r"species",
    r"ecology",
    r"population",
    r"community",
    r"ecosystem",
    r"food\s*chain",
    r"food\s*web",
    r"producer",
    r"consumer",
    r"decomposer",
    r"carbohydrate",
    r"antibody",
    r"antigen",
    r"immunity",
    r"immune\s*system",
    r"organism",
    r"tissue",
    r"organ",
    r"organ\s*system",
    r"homeostasis",
    r"metabolism",
]

# === HISTORY/GEOGRAPHY ===
HISTORY_GEOGRAPHY_PATTERNS = [
    r"tư\s*thục",
    r"công\s*lập",
    r"cách\s*mạng",
    r"khởi\s*nghĩa",
    r"chiến\s*tranh",
    r"độc\s*lập",
    r"thống\s*nhất",
    r"giải\s*phóng",
    r"đảng",
    r"đảng\s*cộng\s*sản",
    r"chủ\s*nghĩa",
    r"chủ\s*nghĩa\s*xã\s*hội",
    r"chủ\s*nghĩa\s*tư\s*bản",
    r"chủ\s*nghĩa\s*đế\s*quốc",
    r"xã\s*hội",
    r"tư\s*bản",
    r"phong\s*kiến",
    r"thuộc\s*địa",
    r"đế\s*quốc",
    r"dân\s*tộc",
    r"văn\s*hóa",
    r"kinh\s*tế",
    r"chính\s*trị",
    r"quân\s*sự",
    r"ngoại\s*giao",
    r"hiệp\s*định",
    r"hiệp\s*ước",
    r"công\s*nghiệp\s*hóa",
    r"hiện\s*đại\s*hóa",
    r"đổi\s*mới",
    r"hội\s*nhập",
    # Geography
    r"lục\s*địa",
    r"đại\s*dương",
    r"biển",
    r"sông",
    r"núi",
    r"đồng\s*bằng",
    r"cao\s*nguyên",
    r"khí\s*hậu",
    r"nhiệt\s*đới",
    r"ôn\s*đới",
    r"hàn\s*đới",
    r"gió\s*mùa",
    r"dân\s*số",
    r"mật\s*độ",
    r"đô\s*thị\s*hóa",
    r"tài\s*nguyên",
    r"khoáng\s*sản",
]

# === PHILOSOPHY/REASONING ===
PHILOSOPHY_REASONING_PATTERNS = [
    r"duy\s*vật",
    r"duy\s*vật\s*biện\s*chứng",
    r"duy\s*vật\s*lịch\s*sử",
    r"duy\s*tâm",
    r"biện\s*chứng",
    r"siêu\s*hình",
    r"ý\s*thức",
    r"vật\s*chất",
    r"tồn\s*tại",
    r"tư\s*duy",
    r"nhận\s*thức",
    r"bản\s*chất",
    r"hiện\s*tượng",
    r"nội\s*dung",
    r"hình\s*thức",
    r"nguyên\s*nhân",
    r"kết\s*quả",
    r"tất\s*nhiên",
    r"ngẫu\s*nhiên",
    r"khả\s*năng",
    r"hiện\s*thực",
    r"mâu\s*thuẫn",
    r"thống\s*nhất",
    r"đối\s*lập",
    r"phủ\s*định",
    r"phủ\s*định\s*của\s*phủ\s*định",
    r"lượng",
    r"chất",
    r"độ",
    r"bước\s*nhảy",
    r"quy\s*luật",
    r"phạm\s*trù",
    r"logic",
    r"logic\s*hình\s*thức",
    r"suy\s*luận",
    r"quy\s*nạp",
    r"diễn\s*dịch",
    r"phân\s*tích",
    r"tổng\s*hợp",
    r"so\s*sánh",
    r"trừu\s*tượng\s*hóa",
    r"khái\s*quát\s*hóa",
    r"phủ\s*định",
    r"khẳng\s*định",
    r"giả\s*thuyết",
    r"giả\s*định",
    r"kết\s*luận",
    r"tiền\s*đề",
    r"luận\s*điểm",
    r"luận\s*cứ",
    r"chứng\s*minh",
    r"bác\s*bỏ",
]

# === ECONOMICS/BUSINESS ===
ECONOMICS_BUSINESS_PATTERNS = [
    r"cung\s*cầu",
    r"cung",
    r"cầu",
    r"thị\s*trường",
    r"giá\s*cả",
    r"giá\s*trị",
    r"giá\s*trị\s*sử\s*dụng",
    r"giá\s*trị\s*trao\s*đổi",
    r"lợi\s*nhuận",
    r"giá\s*trị\s*thặng\s*dư",
    r"doanh\s*thu",
    r"chi\s*phí",
    r"vốn",
    r"tư\s*bản",
    r"đầu\s*tư",
    r"lãi\s*suất",
    r"thuế",
    r"ngân\s*sách",
    r"tài\s*chính",
    r"tiền\s*tệ",
    r"lạm\s*phát",
    r"giảm\s*phát",
    r"thất\s*nghiệp",
    r"việc\s*làm",
    r"gdp",
    r"gnp",
    r"gni",
    r"hdi",
    r"xuất\s*khẩu",
    r"nhập\s*khẩu",
    r"cán\s*cân\s*thương\s*mại",
    r"tỷ\s*giá",
    r"ngoại\s*hối",
    r"chứng\s*khoán",
    r"cổ\s*phiếu",
    r"trái\s*phiếu",
    r"ngân\s*hàng",
    r"tín\s*dụng",
    r"bảo\s*hiểm",
    r"doanh\s*nghiệp",
    r"công\s*ty",
    r"tập\s*đoàn",
    r"startup",
    r"marketing",
    r"quản\s*lý",
    r"quản\s*trị",
    r"nhân\s*sự",
    r"logistics",
    r"chuỗi\s*cung\s*ứng",
]

# === LAW ===
LAW_PATTERNS = [
    r"hiến\s*pháp",
    r"pháp\s*luật",
    r"luật",
    r"bộ\s*luật",
    r"nghị\s*định",
    r"thông\s*tư",
    r"quyết\s*định",
    r"quy\s*phạm",
    r"quy\s*phạm\s*pháp\s*luật",
    r"chủ\s*thể",
    r"khách\s*thể",
    r"quyền",
    r"nghĩa\s*vụ",
    r"trách\s*nhiệm",
    r"hợp\s*đồng",
    r"giao\s*dịch",
    r"sở\s*hữu",
    r"tài\s*sản",
    r"thừa\s*kế",
    r"hình\s*sự",
    r"dân\s*sự",
    r"hành\s*chính",
    r"lao\s*động",
    r"tố\s*tụng",
    r"khởi\s*kiện",
    r"bị\s*cáo",
    r"nguyên\s*đơn",
    r"bị\s*đơn",
    r"tòa\s*án",
    r"viện\s*kiểm\s*sát",
]

# === ENGLISH/LINGUISTICS ===
LINGUISTICS_PATTERNS = [
    r"noun",
    r"verb",
    r"adjective",
    r"adverb",
    r"pronoun",
    r"preposition",
    r"conjunction",
    r"article",
    r"tense",
    r"present\s*simple",
    r"past\s*simple",
    r"present\s*perfect",
    r"past\s*perfect",
    r"future\s*simple",
    r"passive\s*voice",
    r"active\s*voice",
    r"conditional",
    r"subjunctive",
    r"gerund",
    r"infinitive",
    r"participle",
    r"clause",
    r"phrase",
    r"sentence",
    r"paragraph",
    r"essay",
    r"thesis",
    r"topic\s*sentence",
    r"supporting\s*sentence",
    r"conclusion",
    r"introduction",
    r"body",
]


def get_all_patterns():
    # Return all patterns combined into a single list
    all_patterns = []
    all_patterns.extend(GENERAL_PATTERNS)
    all_patterns.extend(IT_PROGRAMMING_PATTERNS)
    all_patterns.extend(IT_DATABASE_PATTERNS)
    all_patterns.extend(IT_NETWORKING_PATTERNS)
    all_patterns.extend(IT_SECURITY_PATTERNS)
    all_patterns.extend(IT_WEB_SOFTWARE_PATTERNS)
    all_patterns.extend(IT_AI_ML_PATTERNS)
    all_patterns.extend(MATH_PATTERNS)
    all_patterns.extend(PHYSICS_PATTERNS)
    all_patterns.extend(CHEMISTRY_PATTERNS)
    all_patterns.extend(BIOLOGY_PATTERNS)
    all_patterns.extend(HISTORY_GEOGRAPHY_PATTERNS)
    all_patterns.extend(PHILOSOPHY_REASONING_PATTERNS)
    all_patterns.extend(ECONOMICS_BUSINESS_PATTERNS)
    all_patterns.extend(LAW_PATTERNS)
    all_patterns.extend(LINGUISTICS_PATTERNS)
    return all_patterns


def get_patterns_by_category(category: str):
    # Return patterns for a specific category
    categories = {
        "general": GENERAL_PATTERNS,
        "it_programming": IT_PROGRAMMING_PATTERNS,
        "it_database": IT_DATABASE_PATTERNS,
        "it_networking": IT_NETWORKING_PATTERNS,
        "it_security": IT_SECURITY_PATTERNS,
        "it_web": IT_WEB_SOFTWARE_PATTERNS,
        "it_ai_ml": IT_AI_ML_PATTERNS,
        "math": MATH_PATTERNS,
        "physics": PHYSICS_PATTERNS,
        "chemistry": CHEMISTRY_PATTERNS,
        "biology": BIOLOGY_PATTERNS,
        "history_geography": HISTORY_GEOGRAPHY_PATTERNS,
        "philosophy": PHILOSOPHY_REASONING_PATTERNS,
        "economics": ECONOMICS_BUSINESS_PATTERNS,
        "law": LAW_PATTERNS,
        "linguistics": LINGUISTICS_PATTERNS,
    }
    return categories.get(category.lower(), [])


# EXTENDED PATTERNS
EXTENDED_IT_PATTERNS = [
    # Software Engineering
    r"waterfall", r"spiral", r"kanban", r"lean",
    r"requirement", r"specification", r"design\s*pattern",
    r"singleton", r"factory", r"observer", r"decorator",
    r"dependency\s*injection", r"solid", r"dry", r"kiss",
    r"refactoring", r"code\s*review", r"pair\s*programming",
    r"technical\s*debt", r"legacy\s*code", r"sprint",
    r"backlog", r"user\s*story", r"epic", r"milestone",
    # Data Science
    r"big\s*data", r"hadoop", r"spark", r"kafka",
    r"etl", r"data\s*warehouse", r"data\s*lake",
    r"data\s*mining", r"data\s*visualization",
    r"tableau", r"power\s*bi", r"matplotlib", r"seaborn",
    r"jupyter", r"notebook", r"colab",
    # Mobile Development
    r"android", r"ios", r"flutter", r"react\s*native",
    r"xamarin", r"cordova", r"ionic",
    r"apk", r"ipa", r"app\s*store", r"play\s*store",
    # Game Development
    r"unity", r"unreal", r"godot", r"pygame",
    r"sprite", r"texture", r"shader", r"rendering",
    r"game\s*loop", r"collision\s*detection", r"physics\s*engine",
    # DevOps Extended
    r"jenkins", r"gitlab\s*ci", r"github\s*actions",
    r"ansible", r"terraform", r"puppet", r"chef",
    r"prometheus", r"grafana", r"elk", r"logging",
    r"monitoring", r"alerting", r"scaling",
    r"load\s*balancing", r"auto\s*scaling", r"blue\s*green",
    r"canary\s*deployment", r"rolling\s*update",
]

EXTENDED_SCIENCE_PATTERNS = [
    # Advanced Physics
    r"lượng\s*tử", r"tương\s*đối", r"hạt\s*cơ\s*bản",
    r"photon", r"quark", r"lepton", r"boson",
    r"higgs", r"entropy", r"năng\s*lượng\s*tối",
    r"vật\s*chất\s*tối", r"lỗ\s*đen", r"siêu\s*tân\s*tinh",
    r"phóng\s*xạ", r"hạt\s*alpha", r"hạt\s*beta",
    r"tia\s*gamma", r"bán\s*rã",
    # Advanced Chemistry
    r"đồng\s*phân", r"cấu\s*trúc", r"hóa\s*lập\s*thể",
    r"cơ\s*chế\s*phản\s*ứng", r"xúc\s*tác\s*sinh\s*học",
    r"hóa\s*phân\s*tích", r"hóa\s*lý", r"hóa\s*sinh",
    r"polymer", r"monomer", r"trùng\s*hợp",
    r"trùng\s*ngưng", r"cao\s*phân\s*tử",
    # Advanced Biology
    r"crispr", r"pcr", r"sequencing",
    r"bioinformatics", r"proteomics", r"genomics",
    r"stem\s*cell", r"tế\s*bào\s*gốc", r"clone",
    r"vaccine", r"kháng\s*sinh", r"vi\s*khuẩn",
    r"virus", r"nấm", r"ký\s*sinh\s*trùng",
    # Medicine
    r"chẩn\s*đoán", r"điều\s*trị", r"phẫu\s*thuật",
    r"nội\s*khoa", r"ngoại\s*khoa", r"sản\s*khoa",
    r"nhi\s*khoa", r"ung\s*thư", r"tim\s*mạch",
    r"thần\s*kinh", r"tiêu\s*hóa", r"hô\s*hấp",
]

EXTENDED_BUSINESS_PATTERNS = [
    # Accounting
    r"kế\s*toán", r"sổ\s*sách", r"bảng\s*cân\s*đối",
    r"lãi\s*lỗ", r"tài\s*sản", r"nợ\s*phải\s*trả",
    r"vốn\s*chủ\s*sở\s*hữu", r"khấu\s*hao",
    r"phân\s*bổ", r"dự\s*phòng",
    # Human Resources
    r"tuyển\s*dụng", r"đào\s*tạo", r"đánh\s*giá",
    r"lương", r"thưởng", r"phúc\s*lợi",
    r"hợp\s*đồng\s*lao\s*động", r"sa\s*thải",
    r"nghỉ\s*việc", r"thăng\s*chức",
    # Operations
    r"sản\s*xuất", r"chất\s*lượng", r"qc",
    r"iso", r"lean\s*manufacturing", r"six\s*sigma",
    r"tồn\s*kho", r"jit", r"erp", r"crm",
    # Strategy
    r"swot", r"pestel", r"porter",
    r"bcg\s*matrix", r"ansoff", r"core\s*competency",
    r"competitive\s*advantage", r"value\s*chain",
]

EXTENDED_HUMANITIES_PATTERNS = [
    # Literature
    r"văn\s*học", r"thơ", r"truyện\s*ngắn",
    r"tiểu\s*thuyết", r"kịch", r"bi\s*kịch",
    r"hài\s*kịch", r"nhân\s*vật", r"cốt\s*truyện",
    r"chủ\s*đề", r"tư\s*tưởng", r"phong\s*cách",
    r"ẩn\s*dụ", r"hoán\s*dụ", r"so\s*sánh",
    r"nhân\s*hóa", r"điệp\s*ngữ", r"đối",
    # Psychology
    r"tâm\s*lý", r"hành\s*vi", r"nhận\s*thức",
    r"cảm\s*xúc", r"động\s*cơ", r"nhân\s*cách",
    r"trí\s*nhớ", r"học\s*tập", r"phát\s*triển",
    r"freud", r"piaget", r"maslow",
    r"iq", r"eq", r"stress", r"trầm\s*cảm",
    # Sociology
    r"xã\s*hội\s*học", r"cộng\s*đồng", r"gia\s*đình",
    r"giai\s*cấp", r"bất\s*bình\s*đẳng",
    r"phân\s*tầng", r"di\s*cư", r"đô\s*thị",
    r"nông\s*thôn", r"toàn\s*cầu\s*hóa",
]

# CONTRADICTION PAIRS
# === IT CONTRADICTIONS ===
IT_CONTRADICTIONS = [
    # Programming paradigms
    ("thông dịch", "biên dịch"),
    ("biên dịch", "thông dịch"),
    ("interpreted", "compiled"),
    ("compiled", "interpreted"),
    ("hướng đối tượng", "hướng thủ tục"),
    ("hướng thủ tục", "hướng đối tượng"),
    ("oop", "procedural"),
    ("procedural", "oop"),
    ("đồng bộ", "bất đồng bộ"),
    ("bất đồng bộ", "đồng bộ"),
    ("synchronous", "asynchronous"),
    ("asynchronous", "synchronous"),
    ("sync", "async"),
    ("async", "sync"),
    # Language types (markup vs programming)
    ("ngôn ngữ đánh dấu", "ngôn ngữ lập trình"),
    ("ngôn ngữ lập trình", "ngôn ngữ đánh dấu"),
    ("đánh dấu", "lập trình"),
    ("lập trình", "đánh dấu"),
    ("markup language", "programming language"),
    ("programming language", "markup language"),
    ("markup", "programming"),
    ("programming", "markup"),
    # Database
    ("sql", "nosql"),
    ("nosql", "sql"),
    ("relational", "non-relational"),
    ("non-relational", "relational"),
    ("acid", "base"),
    ("base", "acid"),
    ("normalization", "denormalization"),
    ("denormalization", "normalization"),
    ("chuẩn hóa", "phi chuẩn hóa"),
    ("phi chuẩn hóa", "chuẩn hóa"),
    # Architecture
    ("monolithic", "microservice"),
    ("microservice", "monolithic"),
    ("frontend", "backend"),
    ("backend", "frontend"),
    ("client", "server"),
    ("server", "client"),
    ("stateful", "stateless"),
    ("stateless", "stateful"),
    # Security
    ("public key", "private key"),
    ("private key", "public key"),
    ("encryption", "decryption"),
    ("decryption", "encryption"),
    ("mã hóa", "giải mã"),
    ("giải mã", "mã hóa"),
    ("symmetric", "asymmetric"),
    ("asymmetric", "symmetric"),
    ("authentication", "authorization"),
    ("authorization", "authentication"),
    ("xác thực", "phân quyền"),
    ("phân quyền", "xác thực"),
    # Networking
    ("tcp", "udp"),
    ("udp", "tcp"),
    ("lan", "wan"),
    ("wan", "lan"),
    ("ipv4", "ipv6"),
    ("ipv6", "ipv4"),
    ("unicast", "broadcast"),
    ("broadcast", "unicast"),
    ("multicast", "unicast"),
    # Development
    ("production", "development"),
    ("development", "production"),
    ("debug", "release"),
    ("release", "debug"),
    ("waterfall", "agile"),
    ("agile", "waterfall"),
    ("push", "pull"),
    ("pull", "push"),
    ("git push", "git pull"),
    ("git pull", "git push"),
    # Data structures
    ("stack", "queue"),
    ("queue", "stack"),
    ("lifo", "fifo"),
    ("fifo", "lifo"),
    ("array", "linked list"),
    ("linked list", "array"),
    ("tree", "graph"),
    ("breadth first", "depth first"),
    ("depth first", "breadth first"),
    ("bfs", "dfs"),
    ("dfs", "bfs"),
    # Types
    ("static typing", "dynamic typing"),
    ("dynamic typing", "static typing"),
    ("strong typing", "weak typing"),
    ("weak typing", "strong typing"),
    ("mutable", "immutable"),
    ("immutable", "mutable"),
    # Machine Learning
    ("supervised", "unsupervised"),
    ("unsupervised", "supervised"),
    ("học có giám sát", "học không giám sát"),
    ("học không giám sát", "học có giám sát"),
    ("classification", "regression"),
    ("regression", "classification"),
    ("phân loại", "hồi quy"),
    ("hồi quy", "phân loại"),
    ("overfitting", "underfitting"),
    ("underfitting", "overfitting"),
    ("training", "inference"),
    ("inference", "training"),
    ("batch", "online"),
    ("online", "batch"),
    # AI/ML conceptual contradictions
    ("related", "unrelated"),
    ("unrelated", "related"),
    ("subset", "superset"),
    ("superset", "subset"),
    ("part of", "separate from"),
    ("separate from", "part of"),
    ("enables", "prevents"),
    ("prevents", "enables"),
    ("machine learning", "not machine learning"),
    ("artificial intelligence", "not artificial intelligence"),
    ("learning", "not learning"),
    ("intelligent", "not intelligent"),
    ("ai", "not ai"),
    ("ml", "not ml"),
    # General semantic contradictions
    ("is", "is not"),
    ("is not", "is"),
    ("can", "cannot"),
    ("cannot", "can"),
    ("does", "does not"),
    ("does not", "does"),
    ("has", "has not"),
    ("has not", "has"),
    ("with", "without"),
    ("without", "with"),
    ("include", "exclude"),
    ("exclude", "include"),
    ("enables", "disables"),
    ("disables", "enables"),
    ("supports", "does not support"),
    ("connected", "disconnected"),
    ("disconnected", "connected"),
    ("dependent", "independent"),
    ("independent", "dependent"),
]

# === EDUCATION CONTRADICTIONS ===
EDUCATION_CONTRADICTIONS = [
    ("tư thục", "công lập"),
    ("công lập", "tư thục"),
    ("tư nhân", "công lập"),
    ("công lập", "tư nhân"),
    ("private", "public"),
    ("public", "private"),
    ("online", "offline"),
    ("offline", "online"),
    ("trực tuyến", "trực tiếp"),
    ("trực tiếp", "trực tuyến"),
    ("lý thuyết", "thực hành"),
    ("thực hành", "lý thuyết"),
    ("theory", "practice"),
    ("practice", "theory"),
    ("chuyên ngành", "đại cương"),
    ("đại cương", "chuyên ngành"),
    ("bắt buộc", "tự chọn"),
    ("tự chọn", "bắt buộc"),
    ("required", "elective"),
    ("elective", "required"),
    ("đại học", "cao đẳng"),
    ("cao đẳng", "đại học"),
    ("undergraduate", "graduate"),
    ("graduate", "undergraduate"),
    ("cử nhân", "thạc sĩ"),
    ("thạc sĩ", "cử nhân"),
    ("thạc sĩ", "tiến sĩ"),
    ("tiến sĩ", "thạc sĩ"),
]

# === PHILOSOPHY CONTRADICTIONS ===
PHILOSOPHY_CONTRADICTIONS = [
    ("duy vật", "duy tâm"),
    ("duy tâm", "duy vật"),
    ("materialism", "idealism"),
    ("idealism", "materialism"),
    ("biện chứng", "siêu hình"),
    ("siêu hình", "biện chứng"),
    ("dialectic", "metaphysic"),
    ("metaphysic", "dialectic"),
    ("vật chất", "ý thức"),
    ("ý thức", "vật chất"),
    ("matter", "consciousness"),
    ("consciousness", "matter"),
    ("tồn tại", "không tồn tại"),
    ("không tồn tại", "tồn tại"),
    ("tất nhiên", "ngẫu nhiên"),
    ("ngẫu nhiên", "tất nhiên"),
    ("necessary", "contingent"),
    ("contingent", "necessary"),
    ("bản chất", "hiện tượng"),
    ("hiện tượng", "bản chất"),
    ("essence", "phenomenon"),
    ("phenomenon", "essence"),
    ("nội dung", "hình thức"),
    ("hình thức", "nội dung"),
    ("content", "form"),
    ("form", "content"),
    ("nguyên nhân", "kết quả"),
    ("kết quả", "nguyên nhân"),
    ("cause", "effect"),
    ("effect", "cause"),
    ("khả năng", "hiện thực"),
    ("hiện thực", "khả năng"),
    ("possibility", "reality"),
    ("reality", "possibility"),
    ("cái riêng", "cái chung"),
    ("cái chung", "cái riêng"),
    ("particular", "universal"),
    ("universal", "particular"),
    ("đối lập", "thống nhất"),
    ("thống nhất", "đối lập"),
    ("lượng", "chất"),
    ("chất", "lượng"),
    ("quantity", "quality"),
    ("quality", "quantity"),
    ("phủ định", "khẳng định"),
    ("khẳng định", "phủ định"),
    ("negation", "affirmation"),
    ("affirmation", "negation"),
    ("quy nạp", "diễn dịch"),
    ("diễn dịch", "quy nạp"),
    ("induction", "deduction"),
    ("deduction", "induction"),
    ("phân tích", "tổng hợp"),
    ("tổng hợp", "phân tích"),
    ("analysis", "synthesis"),
    ("synthesis", "analysis"),
    ("trừu tượng", "cụ thể"),
    ("cụ thể", "trừu tượng"),
    ("abstract", "concrete"),
    ("concrete", "abstract"),
    ("chủ quan", "khách quan"),
    ("khách quan", "chủ quan"),
    ("subjective", "objective"),
    ("objective", "subjective"),
    ("duy lý", "duy cảm"),
    ("duy cảm", "duy lý"),
    ("rationalism", "empiricism"),
    ("empiricism", "rationalism"),
]

# === POLITICS/HISTORY CONTRADICTIONS ===
POLITICS_HISTORY_CONTRADICTIONS = [
    ("xã hội chủ nghĩa", "tư bản chủ nghĩa"),
    ("tư bản chủ nghĩa", "xã hội chủ nghĩa"),
    ("socialism", "capitalism"),
    ("capitalism", "socialism"),
    ("cộng sản", "tư bản"),
    ("tư bản", "cộng sản"),
    ("communist", "capitalist"),
    ("capitalist", "communist"),
    ("dân chủ", "độc tài"),
    ("độc tài", "dân chủ"),
    ("democracy", "dictatorship"),
    ("dictatorship", "democracy"),
    ("cách mạng", "phản cách mạng"),
    ("phản cách mạng", "cách mạng"),
    ("revolution", "counter-revolution"),
    ("thuộc địa", "độc lập"),
    ("độc lập", "thuộc địa"),
    ("colony", "independence"),
    ("independence", "colony"),
    ("đế quốc", "thuộc địa"),
    ("thực dân", "dân tộc"),
    ("dân tộc", "thực dân"),
    ("phong kiến", "tư bản"),
    ("tư bản", "phong kiến"),
    ("feudal", "bourgeois"),
    ("bourgeois", "feudal"),
    ("chiến tranh", "hòa bình"),
    ("hòa bình", "chiến tranh"),
    ("war", "peace"),
    ("peace", "war"),
    ("tấn công", "phòng thủ"),
    ("phòng thủ", "tấn công"),
    ("offense", "defense"),
    ("defense", "offense"),
    ("thắng", "thua"),
    ("thua", "thắng"),
    ("victory", "defeat"),
    ("defeat", "victory"),
    ("đồng minh", "đối thủ"),
    ("đối thủ", "đồng minh"),
    ("ally", "enemy"),
    ("enemy", "ally"),
    ("bảo thủ", "cấp tiến"),
    ("cấp tiến", "bảo thủ"),
    ("conservative", "progressive"),
    ("progressive", "conservative"),
    ("tả", "hữu"),
    ("hữu", "tả"),
    ("left", "right"),
    ("right", "left"),
]

# === ECONOMICS CONTRADICTIONS ===
ECONOMICS_CONTRADICTIONS = [
    ("cung", "cầu"),
    ("cầu", "cung"),
    ("supply", "demand"),
    ("demand", "supply"),
    ("xuất khẩu", "nhập khẩu"),
    ("nhập khẩu", "xuất khẩu"),
    ("export", "import"),
    ("import", "export"),
    ("lạm phát", "giảm phát"),
    ("giảm phát", "lạm phát"),
    ("inflation", "deflation"),
    ("deflation", "inflation"),
    ("thặng dư", "thâm hụt"),
    ("thâm hụt", "thặng dư"),
    ("surplus", "deficit"),
    ("deficit", "surplus"),
    ("tăng trưởng", "suy thoái"),
    ("suy thoái", "tăng trưởng"),
    ("growth", "recession"),
    ("recession", "growth"),
    ("doanh thu", "chi phí"),
    ("chi phí", "doanh thu"),
    ("revenue", "cost"),
    ("cost", "revenue"),
    ("lợi nhuận", "lỗ"),
    ("lỗ", "lợi nhuận"),
    ("profit", "loss"),
    ("loss", "profit"),
    ("tài sản", "nợ"),
    ("nợ", "tài sản"),
    ("asset", "liability"),
    ("liability", "asset"),
    ("vốn", "nợ"),
    ("nợ", "vốn"),
    ("equity", "debt"),
    ("debt", "equity"),
    ("ngắn hạn", "dài hạn"),
    ("dài hạn", "ngắn hạn"),
    ("short term", "long term"),
    ("long term", "short term"),
    ("cố định", "lưu động"),
    ("lưu động", "cố định"),
    ("fixed", "current"),
    ("current", "fixed"),
    ("bán buôn", "bán lẻ"),
    ("bán lẻ", "bán buôn"),
    ("wholesale", "retail"),
    ("retail", "wholesale"),
    ("độc quyền", "cạnh tranh"),
    ("cạnh tranh", "độc quyền"),
    ("monopoly", "competition"),
    ("competition", "monopoly"),
    ("kinh tế thị trường", "kinh tế kế hoạch"),
    ("kinh tế kế hoạch", "kinh tế thị trường"),
    ("market economy", "planned economy"),
    ("planned economy", "market economy"),
]

# === SCIENCE CONTRADICTIONS ===
SCIENCE_CONTRADICTIONS = [
    # Physics
    ("động năng", "thế năng"),
    ("thế năng", "động năng"),
    ("kinetic energy", "potential energy"),
    ("potential energy", "kinetic energy"),
    ("dương", "âm"),
    ("âm", "dương"),
    ("positive", "negative"),
    ("negative", "positive"),
    ("hút", "đẩy"),
    ("đẩy", "hút"),
    ("attract", "repel"),
    ("repel", "attract"),
    ("nóng", "lạnh"),
    ("lạnh", "nóng"),
    ("hot", "cold"),
    ("cold", "hot"),
    ("tăng", "giảm"),
    ("giảm", "tăng"),
    ("increase", "decrease"),
    ("decrease", "increase"),
    ("nhanh", "chậm"),
    ("chậm", "nhanh"),
    ("fast", "slow"),
    ("slow", "fast"),
    ("cao", "thấp"),
    ("thấp", "cao"),
    ("high", "low"),
    ("low", "high"),
    ("lớn", "nhỏ"),
    ("nhỏ", "lớn"),
    ("big", "small"),
    ("small", "big"),
    ("nhiều", "ít"),
    ("ít", "nhiều"),
    ("more", "less"),
    ("less", "more"),
    ("mạnh", "yếu"),
    ("yếu", "mạnh"),
    ("strong", "weak"),
    ("weak", "strong"),
    ("nặng", "nhẹ"),
    ("nhẹ", "nặng"),
    ("heavy", "light"),
    ("light", "heavy"),
    ("rắn", "lỏng"),
    ("lỏng", "rắn"),
    ("solid", "liquid"),
    ("liquid", "solid"),
    ("lỏng", "khí"),
    ("khí", "lỏng"),
    ("liquid", "gas"),
    ("gas", "liquid"),
    ("sóng dọc", "sóng ngang"),
    ("sóng ngang", "sóng dọc"),
    ("longitudinal", "transverse"),
    ("transverse", "longitudinal"),
    ("phản xạ", "khúc xạ"),
    ("khúc xạ", "phản xạ"),
    ("reflection", "refraction"),
    ("refraction", "reflection"),
    ("hấp thụ", "phát xạ"),
    ("phát xạ", "hấp thụ"),
    ("absorption", "emission"),
    ("emission", "absorption"),
    ("cổ điển", "lượng tử"),
    ("lượng tử", "cổ điển"),
    ("classical", "quantum"),
    ("quantum", "classical"),
    # Chemistry
    ("axit", "bazơ"),
    ("bazơ", "axit"),
    ("acid", "base"),
    ("base", "acid"),
    ("oxi hóa", "khử"),
    ("khử", "oxi hóa"),
    ("oxidation", "reduction"),
    ("reduction", "oxidation"),
    ("thu nhiệt", "tỏa nhiệt"),
    ("tỏa nhiệt", "thu nhiệt"),
    ("endothermic", "exothermic"),
    ("exothermic", "endothermic"),
    ("thuận nghịch", "bất thuận nghịch"),
    ("bất thuận nghịch", "thuận nghịch"),
    ("reversible", "irreversible"),
    ("irreversible", "reversible"),
    ("hữu cơ", "vô cơ"),
    ("vô cơ", "hữu cơ"),
    ("organic", "inorganic"),
    ("inorganic", "organic"),
    ("kim loại", "phi kim"),
    ("phi kim", "kim loại"),
    ("metal", "nonmetal"),
    ("nonmetal", "metal"),
    ("đơn chất", "hợp chất"),
    ("hợp chất", "đơn chất"),
    ("element", "compound"),
    ("compound", "element"),
    ("nguyên chất", "hỗn hợp"),
    ("hỗn hợp", "nguyên chất"),
    ("pure", "mixture"),
    ("mixture", "pure"),
    ("đồng nhất", "không đồng nhất"),
    ("không đồng nhất", "đồng nhất"),
    ("homogeneous", "heterogeneous"),
    ("heterogeneous", "homogeneous"),
    ("bão hòa", "chưa bão hòa"),
    ("chưa bão hòa", "bão hòa"),
    ("saturated", "unsaturated"),
    ("unsaturated", "saturated"),
    ("cation", "anion"),
    ("anion", "cation"),
    # Biology
    ("hô hấp", "quang hợp"),
    ("quang hợp", "hô hấp"),
    ("respiration", "photosynthesis"),
    ("photosynthesis", "respiration"),
    ("đồng hóa", "dị hóa"),
    ("dị hóa", "đồng hóa"),
    ("anabolism", "catabolism"),
    ("catabolism", "anabolism"),
    ("nguyên phân", "giảm phân"),
    ("giảm phân", "nguyên phân"),
    ("mitosis", "meiosis"),
    ("meiosis", "mitosis"),
    ("trội", "lặn"),
    ("lặn", "trội"),
    ("dominant", "recessive"),
    ("recessive", "dominant"),
    ("đột biến", "bình thường"),
    ("bình thường", "đột biến"),
    ("mutation", "normal"),
    ("normal", "mutation"),
    ("di truyền", "biến dị"),
    ("biến dị", "di truyền"),
    ("heredity", "variation"),
    ("variation", "heredity"),
    ("đực", "cái"),
    ("cái", "đực"),
    ("male", "female"),
    ("female", "male"),
    ("động vật", "thực vật"),
    ("thực vật", "động vật"),
    ("animal", "plant"),
    ("plant", "animal"),
    ("ký sinh", "cộng sinh"),
    ("cộng sinh", "ký sinh"),
    ("parasite", "symbiont"),
    ("symbiont", "parasite"),
    ("sinh vật sản xuất", "sinh vật tiêu thụ"),
    ("sinh vật tiêu thụ", "sinh vật sản xuất"),
    ("producer", "consumer"),
    ("consumer", "producer"),
    ("sống", "chết"),
    ("chết", "sống"),
    ("alive", "dead"),
    ("dead", "alive"),
    ("khỏe mạnh", "bệnh tật"),
    ("bệnh tật", "khỏe mạnh"),
    ("healthy", "sick"),
    ("sick", "healthy"),
]

# === MATH CONTRADICTIONS ===
MATH_CONTRADICTIONS = [
    ("chẵn", "lẻ"),
    ("lẻ", "chẵn"),
    ("even", "odd"),
    ("odd", "even"),
    ("dương", "âm"),
    ("âm", "dương"),
    ("positive", "negative"),
    ("negative", "positive"),
    ("hữu hạn", "vô hạn"),
    ("vô hạn", "hữu hạn"),
    ("finite", "infinite"),
    ("infinite", "finite"),
    ("hữu tỉ", "vô tỉ"),
    ("vô tỉ", "hữu tỉ"),
    ("rational", "irrational"),
    ("irrational", "rational"),
    ("thực", "ảo"),
    ("ảo", "thực"),
    ("real", "imaginary"),
    ("imaginary", "real"),
    ("đạo hàm", "tích phân"),
    ("tích phân", "đạo hàm"),
    ("derivative", "integral"),
    ("integral", "derivative"),
    ("liên tục", "gián đoạn"),
    ("gián đoạn", "liên tục"),
    ("continuous", "discontinuous"),
    ("discontinuous", "continuous"),
    ("hội tụ", "phân kỳ"),
    ("phân kỳ", "hội tụ"),
    ("convergent", "divergent"),
    ("divergent", "convergent"),
    ("tăng", "giảm"),
    ("giảm", "tăng"),
    ("increasing", "decreasing"),
    ("decreasing", "increasing"),
    ("đơn điệu tăng", "đơn điệu giảm"),
    ("đơn điệu giảm", "đơn điệu tăng"),
    ("cộng", "trừ"),
    ("trừ", "cộng"),
    ("addition", "subtraction"),
    ("subtraction", "addition"),
    ("nhân", "chia"),
    ("chia", "nhân"),
    ("multiplication", "division"),
    ("division", "multiplication"),
    ("lũy thừa", "căn"),
    ("căn", "lũy thừa"),
    ("power", "root"),
    ("root", "power"),
    ("logarit", "mũ"),
    ("mũ", "logarit"),
    ("log", "exponential"),
    ("exponential", "log"),
    ("song song", "cắt nhau"),
    ("cắt nhau", "song song"),
    ("parallel", "intersecting"),
    ("intersecting", "parallel"),
    ("vuông góc", "song song"),
    ("song song", "vuông góc"),
    ("perpendicular", "parallel"),
    ("parallel", "perpendicular"),
    ("nội tiếp", "ngoại tiếp"),
    ("ngoại tiếp", "nội tiếp"),
    ("inscribed", "circumscribed"),
    ("circumscribed", "inscribed"),
    ("đồng biến", "nghịch biến"),
    ("nghịch biến", "đồng biến"),
    ("tỷ lệ thuận", "tỷ lệ nghịch"),
    ("tỷ lệ nghịch", "tỷ lệ thuận"),
    ("directly proportional", "inversely proportional"),
    ("inversely proportional", "directly proportional"),
]

# === GENERAL ANTONYMS ===
GENERAL_CONTRADICTIONS = [
    # Boolean/Logic
    ("có", "không"),
    ("không", "có"),
    ("yes", "no"),
    ("no", "yes"),
    ("true", "false"),
    ("false", "true"),
    ("đúng", "sai"),
    ("sai", "đúng"),
    ("correct", "incorrect"),
    ("incorrect", "correct"),
    ("right", "wrong"),
    ("wrong", "right"),
    # Direction/Position
    ("trên", "dưới"),
    ("dưới", "trên"),
    ("up", "down"),
    ("down", "up"),
    ("trước", "sau"),
    ("sau", "trước"),
    ("before", "after"),
    ("after", "before"),
    ("trong", "ngoài"),
    ("ngoài", "trong"),
    ("inside", "outside"),
    ("outside", "inside"),
    ("trái", "phải"),
    ("phải", "trái"),
    ("left", "right"),
    ("right", "left"),
    ("đầu", "cuối"),
    ("cuối", "đầu"),
    ("start", "end"),
    ("end", "start"),
    ("begin", "finish"),
    ("finish", "begin"),
    ("bắt đầu", "kết thúc"),
    ("kết thúc", "bắt đầu"),
    # Quality
    ("tốt", "xấu"),
    ("xấu", "tốt"),
    ("good", "bad"),
    ("bad", "good"),
    ("đẹp", "xấu"),
    ("xấu", "đẹp"),
    ("beautiful", "ugly"),
    ("ugly", "beautiful"),
    ("mới", "cũ"),
    ("cũ", "mới"),
    ("new", "old"),
    ("old", "new"),
    ("hiện đại", "cổ điển"),
    ("cổ điển", "hiện đại"),
    ("modern", "ancient"),
    ("ancient", "modern"),
    # State - Now protected by BERT bypass (if BERT > 0.75, skip contradiction)
    ("mở", "đóng"),
    ("đóng", "mở"),
    ("open", "close"),
    ("close", "open"),
    ("bật", "tắt"),
    ("tắt", "bật"),
    ("on", "off"),
    ("off", "on"),
    ("hoạt động", "ngừng"),
    ("ngừng", "hoạt động"),
    ("active", "inactive"),
    ("inactive", "active"),
    ("online", "offline"),
    ("offline", "online"),
    # Action - Now protected by BERT bypass (if BERT > 0.75, skip contradiction)
    ("cho", "nhận"),
    ("nhận", "cho"),
    ("give", "take"),
    ("take", "give"),
    ("mua", "bán"),
    ("bán", "mua"),
    ("buy", "sell"),
    ("sell", "buy"),
    ("đến", "đi"),
    ("đi", "đến"),
    ("come", "go"),
    ("go", "come"),
    ("vào", "ra"),
    ("ra", "vào"),
    ("enter", "exit"),
    ("exit", "enter"),
    ("tạo", "xóa"),
    ("xóa", "tạo"),
    ("create", "delete"),
    ("delete", "create"),
    ("thêm", "bớt"),
    ("bớt", "thêm"),
    ("add", "remove"),
    ("remove", "add"),
    # Time
    ("sớm", "muộn"),
    ("muộn", "sớm"),
    ("early", "late"),
    ("late", "early"),
    ("nhanh", "chậm"),
    ("chậm", "nhanh"),
    ("quick", "slow"),
    ("slow", "quick"),
    ("thường xuyên", "hiếm khi"),
    ("hiếm khi", "thường xuyên"),
    ("often", "rarely"),
    ("rarely", "often"),
    ("luôn luôn", "không bao giờ"),
    ("không bao giờ", "luôn luôn"),
    ("always", "never"),
    ("never", "always"),
]

# ADDITIONAL PATTERNS

# === LITERATURE/LANGUAGE PATTERNS ===
LITERATURE_PATTERNS = [
    # Vietnamese
    r"văn\s*học",
    r"thơ",
    r"truyện\s*ngắn",
    r"tiểu\s*thuyết",
    r"kịch",
    r"bi\s*kịch",
    r"hài\s*kịch",
    r"nhân\s*vật",
    r"cốt\s*truyện",
    r"chủ\s*đề",
    r"tư\s*tưởng",
    r"phong\s*cách",
    r"ẩn\s*dụ",
    r"hoán\s*dụ",
    r"so\s*sánh",
    r"nhân\s*hóa",
    r"điệp\s*ngữ",
    r"đối",
    r"phép\s*tu\s*từ",
    r"biện\s*pháp\s*nghệ\s*thuật",
    r"hình\s*ảnh",
    r"biểu\s*tượng",
    r"ngữ\s*pháp",
    r"từ\s*vựng",
    r"câu\s*đơn",
    r"câu\s*ghép",
    r"câu\s*phức",
    r"chủ\s*ngữ",
    r"vị\s*ngữ",
    r"tân\s*ngữ",
    # English
    r"literature",
    r"poetry",
    r"poem",
    r"short\s*story",
    r"novel",
    r"drama",
    r"tragedy",
    r"comedy",
    r"character",
    r"protagonist",
    r"antagonist",
    r"plot",
    r"theme",
    r"motif",
    r"style",
    r"metaphor",
    r"metonymy",
    r"simile",
    r"personification",
    r"repetition",
    r"antithesis",
    r"rhetoric",
    r"literary\s*device",
    r"imagery",
    r"symbol",
    r"symbolism",
    r"grammar",
    r"vocabulary",
    r"simple\s*sentence",
    r"compound\s*sentence",
    r"complex\s*sentence",
    r"subject",
    r"predicate",
    r"object",
    r"alliteration",
    r"hyperbole",
    r"irony",
    r"satire",
    r"foreshadowing",
    r"flashback",
    r"narrative",
    r"narrator",
    r"point\s*of\s*view",
    r"setting",
    r"conflict",
    r"climax",
    r"resolution",
    r"denouement",
]

# === PSYCHOLOGY PATTERNS ===
PSYCHOLOGY_PATTERNS = [
    # Vietnamese
    r"tâm\s*lý",
    r"hành\s*vi",
    r"nhận\s*thức",
    r"cảm\s*xúc",
    r"động\s*cơ",
    r"nhân\s*cách",
    r"trí\s*nhớ",
    r"học\s*tập",
    r"phát\s*triển",
    r"stress",
    r"trầm\s*cảm",
    r"lo\s*âu",
    r"tự\s*kỷ",
    r"tâm\s*thần",
    r"ý\s*thức",
    r"vô\s*thức",
    r"tiềm\s*thức",
    r"bản\s*năng",
    r"phản\s*xạ",
    r"thói\s*quen",
    r"thái\s*độ",
    r"tính\s*cách",
    r"khí\s*chất",
    r"năng\s*lực",
    r"trí\s*tuệ",
    r"cảm\s*giác",
    r"tri\s*giác",
    r"tưởng\s*tượng",
    r"tư\s*duy",
    r"ngôn\s*ngữ",
    # English
    r"psychology",
    r"behavior",
    r"behaviour",
    r"cognition",
    r"cognitive",
    r"emotion",
    r"emotional",
    r"motivation",
    r"personality",
    r"memory",
    r"learning",
    r"development",
    r"depression",
    r"anxiety",
    r"autism",
    r"mental\s*health",
    r"consciousness",
    r"unconscious",
    r"subconscious",
    r"instinct",
    r"reflex",
    r"habit",
    r"attitude",
    r"temperament",
    r"ability",
    r"intelligence",
    r"iq",
    r"eq",
    r"sensation",
    r"perception",
    r"imagination",
    r"thinking",
    r"language",
    r"freud",
    r"piaget",
    r"maslow",
    r"behaviorism",
    r"cognitive\s*psychology",
    r"psychoanalysis",
    r"therapy",
    r"counseling",
]

# === MEDICINE PATTERNS ===
MEDICINE_PATTERNS = [
    # Vietnamese
    r"y\s*học",
    r"bác\s*sĩ",
    r"bệnh\s*nhân",
    r"chẩn\s*đoán",
    r"điều\s*trị",
    r"phẫu\s*thuật",
    r"thuốc",
    r"liều\s*lượng",
    r"triệu\s*chứng",
    r"bệnh",
    r"vi\s*khuẩn",
    r"virus",
    r"nhiễm\s*trùng",
    r"kháng\s*sinh",
    r"vaccine",
    r"miễn\s*dịch",
    r"dị\s*ứng",
    r"viêm",
    r"ung\s*thư",
    r"khối\s*u",
    r"tim\s*mạch",
    r"huyết\s*áp",
    r"tiểu\s*đường",
    r"gan",
    r"thận",
    r"phổi",
    r"dạ\s*dày",
    r"ruột",
    r"xương",
    r"cơ",
    # English
    r"medicine",
    r"doctor",
    r"physician",
    r"patient",
    r"diagnosis",
    r"treatment",
    r"surgery",
    r"medication",
    r"drug",
    r"dosage",
    r"symptom",
    r"disease",
    r"illness",
    r"bacteria",
    r"infection",
    r"antibiotic",
    r"vaccination",
    r"allergy",
    r"inflammation",
    r"cancer",
    r"tumor",
    r"cardiovascular",
    r"blood\s*pressure",
    r"diabetes",
    r"liver",
    r"kidney",
    r"lung",
    r"stomach",
    r"intestine",
    r"bone",
    r"muscle",
    r"surgery",
    r"operation",
    r"anesthesia",
    r"prescription",
    r"pharmacy",
    r"clinic",
    r"hospital",
    r"emergency",
    r"chronic",
    r"acute",
]

# === ARCHITECTURE PATTERNS ===
ARCHITECTURE_PATTERNS = [
    # Vietnamese
    r"kiến\s*trúc",
    r"thiết\s*kế",
    r"xây\s*dựng",
    r"công\s*trình",
    r"tòa\s*nhà",
    r"mặt\s*bằng",
    r"mặt\s*đứng",
    r"mặt\s*cắt",
    r"nền\s*móng",
    r"kết\s*cấu",
    r"vật\s*liệu",
    r"bê\s*tông",
    r"thép",
    r"gạch",
    r"xi\s*măng",
    r"cốt\s*thép",
    r"cột",
    r"dầm",
    r"sàn",
    r"tường",
    r"mái",
    r"cửa",
    r"cầu\s*thang",
    r"thang\s*máy",
    r"điều\s*hòa",
    r"phòng\s*cháy",
    r"thoát\s*nước",
    r"chiếu\s*sáng",
    r"quy\s*hoạch",
    r"đô\s*thị",
    # English
    r"architecture",
    r"design",
    r"construction",
    r"building",
    r"floor\s*plan",
    r"elevation",
    r"section",
    r"foundation",
    r"structure",
    r"structural",
    r"material",
    r"concrete",
    r"steel",
    r"brick",
    r"cement",
    r"reinforcement",
    r"column",
    r"beam",
    r"slab",
    r"wall",
    r"roof",
    r"door",
    r"window",
    r"staircase",
    r"elevator",
    r"air\s*conditioning",
    r"hvac",
    r"fire\s*protection",
    r"drainage",
    r"lighting",
    r"urban\s*planning",
    r"zoning",
    r"blueprint",
    r"cad",
    r"bim",
    r"facade",
    r"interior",
    r"exterior",
    r"landscape",
    r"sustainability",
    r"green\s*building",
]

# === MUSIC/ART PATTERNS ===
MUSIC_ART_PATTERNS = [
    # Vietnamese
    r"âm\s*nhạc",
    r"giai\s*điệu",
    r"nhịp\s*điệu",
    r"hòa\s*âm",
    r"tiết\s*tấu",
    r"nốt\s*nhạc",
    r"hợp\s*âm",
    r"quãng",
    r"thang\s*âm",
    r"giọng",
    r"cao\s*độ",
    r"cường\s*độ",
    r"nhạc\s*cụ",
    r"dàn\s*nhạc",
    r"ca\s*sĩ",
    r"nhạc\s*sĩ",
    r"sáng\s*tác",
    r"biểu\s*diễn",
    r"hội\s*họa",
    r"điêu\s*khắc",
    r"màu\s*sắc",
    r"bố\s*cục",
    r"đường\s*nét",
    r"hình\s*khối",
    r"ánh\s*sáng",
    r"bóng",
    r"phối\s*cảnh",
    r"trường\s*phái",
    r"nghệ\s*thuật",
    r"thẩm\s*mỹ",
    # English
    r"music",
    r"melody",
    r"rhythm",
    r"harmony",
    r"tempo",
    r"note",
    r"chord",
    r"interval",
    r"scale",
    r"key",
    r"pitch",
    r"dynamics",
    r"instrument",
    r"orchestra",
    r"singer",
    r"composer",
    r"composition",
    r"performance",
    r"painting",
    r"sculpture",
    r"color",
    r"colour",
    r"composition",
    r"line",
    r"shape",
    r"form",
    r"light",
    r"shadow",
    r"perspective",
    r"art\s*movement",
    r"art",
    r"aesthetic",
    r"canvas",
    r"brush",
    r"palette",
    r"portrait",
    r"landscape",
    r"still\s*life",
    r"abstract",
    r"impressionism",
    r"realism",
    r"baroque",
    r"renaissance",
]
# === LITERATURE CONTRADICTIONS ===
LITERATURE_CONTRADICTIONS = [
    ("bi kịch", "hài kịch"),
    ("hài kịch", "bi kịch"),
    ("tragedy", "comedy"),
    ("comedy", "tragedy"),
    ("chính diện", "phản diện"),
    ("phản diện", "chính diện"),
    ("protagonist", "antagonist"),
    ("antagonist", "protagonist"),
    ("thực", "hư"),
    ("hư", "thực"),
    ("fiction", "non-fiction"),
    ("non-fiction", "fiction"),
    ("văn xuôi", "văn vần"),
    ("văn vần", "văn xuôi"),
    ("prose", "poetry"),
    ("poetry", "prose"),
    ("cổ điển", "hiện đại"),
    ("hiện đại", "cổ điển"),
    ("classic", "modern"),
    ("modern", "classic"),
    ("trực tiếp", "gián tiếp"),
    ("gián tiếp", "trực tiếp"),
    ("direct", "indirect"),
    ("indirect", "direct"),
]

# === PSYCHOLOGY CONTRADICTIONS ===
PSYCHOLOGY_CONTRADICTIONS = [
    ("ý thức", "vô thức"),
    ("vô thức", "ý thức"),
    ("conscious", "unconscious"),
    ("unconscious", "conscious"),
    ("bẩm sinh", "học được"),
    ("học được", "bẩm sinh"),
    ("innate", "learned"),
    ("learned", "innate"),
    ("nature", "nurture"),
    ("nurture", "nature"),
    ("nội hướng", "ngoại hướng"),
    ("ngoại hướng", "nội hướng"),
    ("introvert", "extrovert"),
    ("extrovert", "introvert"),
    ("lạc quan", "bi quan"),
    ("bi quan", "lạc quan"),
    ("optimistic", "pessimistic"),
    ("pessimistic", "optimistic"),
    ("bình thường", "bất thường"),
    ("bất thường", "bình thường"),
    ("normal", "abnormal"),
    ("abnormal", "normal"),
    ("lý trí", "cảm xúc"),
    ("cảm xúc", "lý trí"),
    ("rational", "emotional"),
    ("emotional", "rational"),
]

# === MEDICINE CONTRADICTIONS ===
MEDICINE_CONTRADICTIONS = [
    ("cấp tính", "mãn tính"),
    ("mãn tính", "cấp tính"),
    ("acute", "chronic"),
    ("chronic", "acute"),
    ("lành tính", "ác tính"),
    ("ác tính", "lành tính"),
    ("benign", "malignant"),
    ("malignant", "benign"),
    ("khỏe mạnh", "bệnh tật"),
    ("bệnh tật", "khỏe mạnh"),
    ("healthy", "diseased"),
    ("diseased", "healthy"),
    ("nhiễm trùng", "vô trùng"),
    ("vô trùng", "nhiễm trùng"),
    ("infected", "sterile"),
    ("sterile", "infected"),
    ("di truyền", "mắc phải"),
    ("mắc phải", "di truyền"),
    ("hereditary", "acquired"),
    ("acquired", "hereditary"),
    ("nội khoa", "ngoại khoa"),
    ("ngoại khoa", "nội khoa"),
    ("internal medicine", "surgery"),
    ("surgery", "internal medicine"),
    ("phòng bệnh", "chữa bệnh"),
    ("chữa bệnh", "phòng bệnh"),
    ("prevention", "treatment"),
    ("treatment", "prevention"),
]

# === ARCHITECTURE CONTRADICTIONS ===
ARCHITECTURE_CONTRADICTIONS = [
    ("nội thất", "ngoại thất"),
    ("ngoại thất", "nội thất"),
    ("interior", "exterior"),
    ("exterior", "interior"),
    ("ngang", "dọc"),
    ("dọc", "ngang"),
    ("horizontal", "vertical"),
    ("vertical", "horizontal"),
    ("cố định", "di động"),
    ("di động", "cố định"),
    ("fixed", "movable"),
    ("movable", "fixed"),
    ("tự nhiên", "nhân tạo"),
    ("nhân tạo", "tự nhiên"),
    ("natural", "artificial"),
    ("artificial", "natural"),
    ("truyền thống", "hiện đại"),
    ("hiện đại", "truyền thống"),
    ("traditional", "modern"),
    ("modern", "traditional"),
    ("đối xứng", "bất đối xứng"),
    ("bất đối xứng", "đối xứng"),
    ("symmetric", "asymmetric"),
    ("asymmetric", "symmetric"),
]

# === MUSIC/ART CONTRADICTIONS ===
MUSIC_ART_CONTRADICTIONS = [
    ("cao", "thấp"),
    ("thấp", "cao"),
    ("high pitch", "low pitch"),
    ("low pitch", "high pitch"),
    ("nhanh", "chậm"),
    ("chậm", "nhanh"),
    ("fast tempo", "slow tempo"),
    ("slow tempo", "fast tempo"),
    ("mạnh", "nhẹ"),
    ("nhẹ", "mạnh"),
    ("forte", "piano"),
    ("piano", "forte"),
    ("trưởng", "thứ"),
    ("thứ", "trưởng"),
    ("major", "minor"),
    ("minor", "major"),
    ("hài hòa", "bất hài hòa"),
    ("bất hài hòa", "hài hòa"),
    ("consonance", "dissonance"),
    ("dissonance", "consonance"),
    ("cụ thể", "trừu tượng"),
    ("trừu tượng", "cụ thể"),
    ("figurative", "abstract"),
    ("abstract", "figurative"),
    ("sáng", "tối"),
    ("tối", "sáng"),
    ("light", "dark"),
    ("dark", "light"),
    ("ấm", "lạnh"),
    ("lạnh", "ấm"),
    ("warm color", "cool color"),
    ("cool color", "warm color"),
]

# === NONSENSE / HALLUCINATION DETECTORS ===
# Common objects/concepts that rarely appear in IT/Math/Science academic answers
# unless specifically asked. Used to detect "AI runs on gasoline" type errors.
NONSENSE_PATTERNS = [
    # Materials/Fuels
    r"xăng", r"dầu\s*diesel", r"dầu\s*hỏa", r"than\s*đá",
    r"gasoline", r"petrol", r"diesel", r"fuel",
    # Food/Drink
    r"\bcơm\b", r"\bphở\b", r"\bbún\b", r"\bmiến\b", r"bánh\s*mì",
    r"\bthịt\b", r"\bcá\b", r"\btrứng\b", r"\bsữa\b",
    r"\bbia\b", r"\brượu\b", r"cà\s*phê", r"nước\s*ngọt",
    r"\bpizza\b", r"\bburger\b", r"\bcoffee\b",
    # Animals
    r"con\s*gà", r"con\s*chó", r"con\s*mèo", r"con\s*bò",
    r"\bchicken\b", r"\bdog\b", r"\bcat\b", r"\bcow\b",
    # Vehicles (context dependent, but suspicious in pure software)
    r"xe\s*máy", r"ô\s*tô", r"xe\s*đạp",
    r"motorbike", r"\bcar\b", r"bicycle",
    # Random Objects
    r"bàn\s*ghế", r"giường\s*tủ", r"quần\s*áo",
    r"furniture", r"clothes",
]

# === ACCOUNTING & FINANCE PATTERNS ===
ACCOUNTING_PATTERNS = [
    # Vietnamese
    r"kế\s*toán", r"sổ\s*sách", r"báo\s*cáo\s*tài\s*chính",
    r"bảng\s*cân\s*đối", r"tài\s*sản", r"nguồn\s*vốn", r"nợ\s*phải\s*trả",
    r"vốn\s*chủ\s*sở\s*hữu", r"doanh\s*thu", r"chi\s*phí", r"lợi\s*nhuận",
    r"khấu\s*hao", r"định\s*khoản", r"ghi\s*sổ", r"bút\s*toán",
    r"thuế", r"VAT", r"thuế\s*GTGT", r"thuế\s*thu\s*nhập",
    r"kiểm\s*toán", r"báo\s*cáo\s*kiểm\s*toán",
    r"chi\s*phí\s*cố\s*định", r"chi\s*phí\s*biến\s*đổi",
    r"điểm\s*hòa\s*vốn", r"biên\s*lợi\s*nhuận",
    r"dòng\s*tiền", r"luồng\s*tiền", r"cash\s*flow",
    r"ROI", r"ROE", r"ROA", r"NPV", r"IRR",
    # English
    r"accounting", r"bookkeeping", r"financial\s*statement",
    r"balance\s*sheet", r"assets", r"liabilities", r"equity",
    r"revenue", r"expense", r"profit", r"loss",
    r"depreciation", r"amortization", r"journal\s*entry",
    r"trial\s*balance", r"ledger", r"accounts\s*receivable",
    r"accounts\s*payable", r"inventory", r"FIFO", r"LIFO",
    r"GAAP", r"IFRS", r"audit", r"internal\s*control",
    r"fixed\s*cost", r"variable\s*cost", r"break-even",
    r"gross\s*margin", r"net\s*margin", r"EBITDA",
]

# === STATISTICS PATTERNS ===
STATISTICS_PATTERNS = [
    # Vietnamese
    r"thống\s*kê", r"xác\s*suất", r"mẫu", r"tổng\s*thể",
    r"trung\s*bình", r"trung\s*vị", r"mốt", r"mode",
    r"độ\s*lệch\s*chuẩn", r"phương\s*sai", r"phân\s*phối",
    r"phân\s*phối\s*chuẩn", r"phân\s*phối\s*nhị\s*thức",
    r"giả\s*thuyết", r"kiểm\s*định", r"p-value",
    r"khoảng\s*tin\s*cậy", r"sai\s*số", r"biên\s*độ\s*sai\s*số",
    r"tương\s*quan", r"hồi\s*quy", r"hệ\s*số\s*tương\s*quan",
    r"R\s*bình\s*phương", r"chi\s*bình\s*phương",
    r"phân\s*tích\s*ANOVA", r"t-test", r"z-test",
    # English
    r"statistics", r"probability", r"sample", r"population",
    r"mean", r"median", r"mode", r"standard\s*deviation",
    r"variance", r"distribution", r"normal\s*distribution",
    r"binomial\s*distribution", r"poisson\s*distribution",
    r"hypothesis", r"significance", r"p-value", r"alpha",
    r"confidence\s*interval", r"margin\s*of\s*error",
    r"correlation", r"regression", r"linear\s*regression",
    r"R-squared", r"chi-square", r"ANOVA", r"t-test", r"z-test",
    r"null\s*hypothesis", r"alternative\s*hypothesis",
    r"type\s*I\s*error", r"type\s*II\s*error",
    r"sampling", r"random\s*sampling", r"stratified\s*sampling",
]

# === MARKETING PATTERNS ===
MARKETING_PATTERNS = [
    # Vietnamese
    r"tiếp\s*thị", r"marketing", r"thương\s*hiệu", r"brand",
    r"phân\s*khúc", r"định\s*vị", r"khách\s*hàng\s*mục\s*tiêu",
    r"4P", r"sản\s*phẩm", r"giá\s*cả", r"phân\s*phối", r"xúc\s*tiến",
    r"quảng\s*cáo", r"PR", r"quan\s*hệ\s*công\s*chúng",
    r"digital\s*marketing", r"SEO", r"SEM", r"social\s*media",
    r"content\s*marketing", r"email\s*marketing",
    r"phễu\s*marketing", r"funnel", r"chuyển\s*đổi", r"conversion",
    r"tỷ\s*lệ\s*chuyển\s*đổi", r"CPC", r"CPM", r"CTR",
    r"B2B", r"B2C", r"thị\s*phần", r"thị\s*trường",
    r"nghiên\s*cứu\s*thị\s*trường", r"khảo\s*sát",
    # English
    r"market\s*research", r"target\s*market", r"segmentation",
    r"positioning", r"branding", r"USP", r"value\s*proposition",
    r"product", r"price", r"place", r"promotion",
    r"advertising", r"public\s*relations", r"publicity",
    r"sales\s*promotion", r"direct\s*marketing",
    r"influencer\s*marketing", r"affiliate\s*marketing",
    r"customer\s*journey", r"touchpoint", r"lead\s*generation",
    r"market\s*share", r"competitive\s*analysis", r"SWOT",
]

# === SOCIOLOGY PATTERNS ===
SOCIOLOGY_PATTERNS = [
    # Vietnamese
    r"xã\s*hội\s*học", r"cấu\s*trúc\s*xã\s*hội", r"thiết\s*chế",
    r"phân\s*tầng\s*xã\s*hội", r"bất\s*bình\s*đẳng",
    r"xã\s*hội\s*hóa", r"giai\s*cấp", r"tầng\s*lớp",
    r"vai\s*trò\s*xã\s*hội", r"địa\s*vị", r"chuẩn\s*mực",
    r"giá\s*trị\s*xã\s*hội", r"văn\s*hóa", r"bản\s*sắc",
    r"gia\s*đình", r"hôn\s*nhân", r"giáo\s*dục",
    r"tôn\s*giáo", r"dân\s*tộc", r"di\s*cư",
    r"đô\s*thị\s*hóa", r"toàn\s*cầu\s*hóa",
    r"phong\s*trào\s*xã\s*hội", r"biến\s*đổi\s*xã\s*hội",
    # English
    r"sociology", r"social\s*structure", r"institution",
    r"social\s*stratification", r"inequality", r"social\s*class",
    r"socialization", r"social\s*role", r"status", r"norms",
    r"culture", r"subculture", r"cultural\s*diversity",
    r"family", r"marriage", r"education\s*system",
    r"religion", r"ethnicity", r"race", r"migration",
    r"urbanization", r"globalization", r"social\s*change",
    r"social\s*movement", r"collective\s*behavior",
    r"deviance", r"crime", r"social\s*control",
]

# === ENVIRONMENTAL SCIENCE PATTERNS ===
ENVIRONMENTAL_PATTERNS = [
    # Vietnamese
    r"môi\s*trường", r"sinh\s*thái", r"hệ\s*sinh\s*thái",
    r"ô\s*nhiễm", r"ô\s*nhiễm\s*không\s*khí", r"ô\s*nhiễm\s*nước",
    r"biến\s*đổi\s*khí\s*hậu", r"hiệu\s*ứng\s*nhà\s*kính",
    r"nóng\s*lên\s*toàn\s*cầu", r"băng\s*tan", r"mực\s*nước\s*biển",
    r"đa\s*dạng\s*sinh\s*học", r"tuyệt\s*chủng", r"bảo\s*tồn",
    r"năng\s*lượng\s*tái\s*tạo", r"năng\s*lượng\s*mặt\s*trời",
    r"năng\s*lượng\s*gió", r"thủy\s*điện", r"sinh\s*khối",
    r"phát\s*triển\s*bền\s*vững", r"rác\s*thải", r"tái\s*chế",
    r"khí\s*thải", r"CO2", r"cacbon", r"carbon\s*footprint",
    r"phá\s*rừng", r"xói\s*mòn", r"sa\s*mạc\s*hóa",
    # English
    r"environment", r"ecology", r"ecosystem", r"biome",
    r"pollution", r"air\s*pollution", r"water\s*pollution",
    r"climate\s*change", r"greenhouse\s*effect", r"global\s*warming",
    r"ozone\s*layer", r"acid\s*rain", r"deforestation",
    r"biodiversity", r"endangered\s*species", r"conservation",
    r"renewable\s*energy", r"solar\s*energy", r"wind\s*energy",
    r"hydropower", r"biomass", r"geothermal",
    r"sustainable\s*development", r"recycling", r"waste\s*management",
    r"carbon\s*footprint", r"emission", r"greenhouse\s*gas",
]

# === ACCOUNTING CONTRADICTIONS ===
ACCOUNTING_CONTRADICTIONS = [
    ("tài sản", "nợ"),
    ("nợ", "tài sản"),
    ("doanh thu", "chi phí"),
    ("chi phí", "doanh thu"),
    ("lợi nhuận", "lỗ"),
    ("lỗ", "lợi nhuận"),
    ("ghi nợ", "ghi có"),
    ("ghi có", "ghi nợ"),
    ("debit", "credit"),
    ("credit", "debit"),
    ("assets", "liabilities"),
    ("liabilities", "assets"),
    ("revenue", "expense"),
    ("expense", "revenue"),
    ("profit", "loss"),
    ("loss", "profit"),
]

# === STATISTICS CONTRADICTIONS ===
STATISTICS_CONTRADICTIONS = [
    ("chấp nhận H0", "bác bỏ H0"),
    ("bác bỏ H0", "chấp nhận H0"),
    ("accept H0", "reject H0"),
    ("reject H0", "accept H0"),
    ("tương quan dương", "tương quan âm"),
    ("tương quan âm", "tương quan dương"),
    ("positive correlation", "negative correlation"),
    ("negative correlation", "positive correlation"),
    ("cao", "thấp"),
    ("thấp", "cao"),
    ("high", "low"),
    ("low", "high"),
]

# === ENVIRONMENTAL CONTRADICTIONS ===
ENVIRONMENTAL_CONTRADICTIONS = [
    ("tái tạo", "không tái tạo"),
    ("không tái tạo", "tái tạo"),
    ("renewable", "non-renewable"),
    ("non-renewable", "renewable"),
    ("bảo tồn", "phá hủy"),
    ("phá hủy", "bảo tồn"),
    ("conservation", "destruction"),
    ("destruction", "conservation"),
    ("tăng", "giảm"),
    ("giảm", "tăng"),
    ("increase", "decrease"),
    ("decrease", "increase"),
    ("sạch", "ô nhiễm"),
    ("ô nhiễm", "sạch"),
    ("clean", "polluted"),
    ("polluted", "clean"),
]


# === DATA STRUCTURES PATTERNS ===
DATA_STRUCTURES_PATTERNS = [
    # Vietnamese
    r"cấu\s*trúc\s*dữ\s*liệu", r"mảng", r"danh\s*sách\s*liên\s*kết",
    r"ngăn\s*xếp", r"hàng\s*đợi", r"cây", r"cây\s*nhị\s*phân",
    r"đồ\s*thị", r"bảng\s*băm", r"heap", r"trie",
    r"duyệt\s*cây", r"duyệt\s*đồ\s*thị", r"BFS", r"DFS",
    r"độ\s*phức\s*tạp", r"big\s*O", r"O\(1\)", r"O\(n\)", r"O\(log\s*n\)",
    r"O\(n\^2\)", r"O\(n\s*log\s*n\)",
    r"sắp\s*xếp", r"tìm\s*kiếm", r"đệ\s*quy",
    # English
    r"data\s*structure", r"array", r"linked\s*list",
    r"stack", r"queue", r"tree", r"binary\s*tree", r"binary\s*search\s*tree",
    r"graph", r"hash\s*table", r"hash\s*map", r"heap", r"trie", r"priority\s*queue",
    r"traversal", r"BFS", r"DFS", r"breadth\s*first", r"depth\s*first",
    r"complexity", r"big\s*O", r"time\s*complexity", r"space\s*complexity",
    r"sorting", r"searching", r"recursion", r"iteration",
    r"bubble\s*sort", r"quick\s*sort", r"merge\s*sort", r"insertion\s*sort",
    r"binary\s*search", r"linear\s*search",
]

# === ALGORITHMS PATTERNS ===
ALGORITHMS_PATTERNS = [
    # Vietnamese
    r"thuật\s*toán", r"giải\s*thuật", r"chia\s*để\s*trị",
    r"quy\s*hoạch\s*động", r"tham\s*lam", r"quay\s*lui",
    r"đường\s*đi\s*ngắn\s*nhất", r"Dijkstra", r"cây\s*khung\s*nhỏ\s*nhất",
    # English
    r"algorithm", r"divide\s*and\s*conquer", r"dynamic\s*programming",
    r"greedy", r"backtracking", r"brute\s*force",
    r"shortest\s*path", r"Dijkstra", r"Bellman-Ford", r"Floyd-Warshall",
    r"minimum\s*spanning\s*tree", r"Kruskal", r"Prim",
    r"topological\s*sort", r"strongly\s*connected",
    r"memoization", r"tabulation",
]

# === MOBILE DEVELOPMENT PATTERNS ===
MOBILE_DEV_PATTERNS = [
    # Vietnamese
    r"ứng\s*dụng\s*di\s*động", r"Android", r"iOS", r"React\s*Native",
    r"Flutter", r"Kotlin", r"Swift", r"Xcode", r"Android\s*Studio",
    r"APK", r"IPA", r"Play\s*Store", r"App\s*Store",
    # English
    r"mobile\s*app", r"native\s*app", r"hybrid\s*app", r"cross-platform",
    r"Android", r"iOS", r"React\s*Native", r"Flutter", r"Xamarin",
    r"Kotlin", r"Swift", r"Objective-C", r"Java\s*Android",
    r"SDK", r"NDK", r"Gradle", r"CocoaPods",
    r"push\s*notification", r"deep\s*link", r"app\s*lifecycle",
]

# === DEVOPS PATTERNS ===
DEVOPS_PATTERNS = [
    # Vietnamese
    r"triển\s*khai", r"tự\s*động\s*hóa", r"pipeline",
    r"container", r"ảo\s*hóa", r"giám\s*sát", r"log",
    # English
    r"DevOps", r"CI/CD", r"continuous\s*integration", r"continuous\s*deployment",
    r"Docker", r"Kubernetes", r"k8s", r"container\s*orchestration",
    r"Jenkins", r"GitLab\s*CI", r"GitHub\s*Actions", r"CircleCI",
    r"Ansible", r"Terraform", r"Chef", r"Puppet",
    r"monitoring", r"logging", r"Prometheus", r"Grafana", r"ELK",
    r"infrastructure\s*as\s*code", r"IaC",
    r"load\s*balancer", r"reverse\s*proxy", r"Nginx", r"HAProxy",
    r"auto\s*scaling", r"blue-green\s*deployment", r"canary\s*deployment",
]

# === TESTING PATTERNS ===
TESTING_PATTERNS = [
    # Vietnamese
    r"kiểm\s*thử", r"test\s*case", r"test\s*plan",
    r"kiểm\s*thử\s*đơn\s*vị", r"kiểm\s*thử\s*tích\s*hợp",
    r"kiểm\s*thử\s*hệ\s*thống", r"kiểm\s*thử\s*chấp\s*nhận",
    r"regression\s*test", r"smoke\s*test",
    # English
    r"testing", r"test\s*case", r"test\s*suite", r"test\s*plan",
    r"unit\s*test", r"integration\s*test", r"system\s*test", r"acceptance\s*test",
    r"regression\s*test", r"smoke\s*test", r"sanity\s*test",
    r"black\s*box", r"white\s*box", r"gray\s*box",
    r"TDD", r"BDD", r"test-driven", r"behavior-driven",
    r"mock", r"stub", r"spy", r"fake",
    r"Jest", r"Mocha", r"JUnit", r"pytest", r"Selenium", r"Cypress",
    r"code\s*coverage", r"test\s*coverage",
]

# === UX/UI DESIGN PATTERNS ===
UX_UI_PATTERNS = [
    # Vietnamese
    r"giao\s*diện\s*người\s*dùng", r"trải\s*nghiệm\s*người\s*dùng",
    r"thiết\s*kế\s*UI", r"thiết\s*kế\s*UX", r"wireframe", r"prototype",
    r"màu\s*sắc", r"font\s*chữ", r"layout", r"responsive",
    # English
    r"user\s*interface", r"user\s*experience", r"UI\s*design", r"UX\s*design",
    r"wireframe", r"mockup", r"prototype", r"Figma", r"Sketch", r"Adobe\s*XD",
    r"color\s*scheme", r"typography", r"layout", r"grid\s*system",
    r"responsive\s*design", r"mobile\s*first", r"accessibility", r"A11Y",
    r"usability", r"information\s*architecture", r"user\s*flow",
    r"heuristic\s*evaluation", r"user\s*testing", r"A/B\s*testing",
]

# === PROJECT MANAGEMENT PATTERNS ===
PROJECT_MGMT_PATTERNS = [
    # Vietnamese
    r"quản\s*lý\s*dự\s*án", r"Gantt", r"milestone", r"deadline",
    r"sprint\s*planning", r"backlog", r"burn-down",
    r"stakeholder", r"scope", r"budget", r"timeline",
    # English
    r"project\s*management", r"Agile", r"Scrum", r"Kanban", r"Waterfall",
    r"sprint", r"iteration", r"backlog", r"user\s*story", r"epic",
    r"Gantt\s*chart", r"milestone", r"deliverable", r"deadline",
    r"scope", r"budget", r"timeline", r"risk\s*management",
    r"stakeholder", r"requirement", r"specification",
    r"Jira", r"Trello", r"Asana", r"Monday",
    r"standup", r"retrospective", r"sprint\s*review",
]

# === BLOCKCHAIN PATTERNS ===
BLOCKCHAIN_PATTERNS = [
    # Vietnamese
    r"chuỗi\s*khối", r"blockchain", r"tiền\s*điện\s*tử", r"cryptocurrency",
    r"Bitcoin", r"Ethereum", r"hợp\s*đồng\s*thông\s*minh",
    r"ví\s*điện\s*tử", r"mining", r"đào\s*coin",
    # English
    r"blockchain", r"distributed\s*ledger", r"decentralized",
    r"cryptocurrency", r"Bitcoin", r"Ethereum", r"altcoin",
    r"smart\s*contract", r"Solidity", r"Web3",
    r"wallet", r"mining", r"proof\s*of\s*work", r"proof\s*of\s*stake",
    r"NFT", r"DeFi", r"DAO", r"token", r"consensus",
    r"hash", r"block", r"transaction", r"gas\s*fee",
]

# === HUMAN RESOURCES PATTERNS ===
HR_PATTERNS = [
    # Vietnamese
    r"nhân\s*sự", r"tuyển\s*dụng", r"phỏng\s*vấn", r"CV", r"resume",
    r"lương", r"thưởng", r"bảo\s*hiểm", r"phúc\s*lợi",
    r"đào\s*tạo", r"phát\s*triển\s*nhân\s*viên", r"KPI",
    # English
    r"human\s*resources", r"HR", r"recruitment", r"hiring",
    r"interview", r"CV", r"resume", r"job\s*description",
    r"salary", r"compensation", r"benefits", r"bonus",
    r"training", r"development", r"performance\s*review",
    r"onboarding", r"offboarding", r"employee\s*engagement",
]

# === COMMUNICATION PATTERNS ===
COMMUNICATION_PATTERNS = [
    # Vietnamese
    r"giao\s*tiếp", r"thuyết\s*trình", r"đàm\s*phán",
    r"email", r"họp", r"báo\s*cáo", r"phản\s*hồi",
    # English
    r"communication", r"presentation", r"negotiation", r"persuasion",
    r"email\s*etiquette", r"meeting", r"conference", r"webinar",
    r"report", r"feedback", r"active\s*listening",
    r"verbal", r"non-verbal", r"written\s*communication",
]

# === ENTREPRENEURSHIP PATTERNS ===
ENTREPRENEURSHIP_PATTERNS = [
    # Vietnamese
    r"khởi\s*nghiệp", r"startup", r"doanh\s*nghiệp",
    r"kế\s*hoạch\s*kinh\s*doanh", r"vốn\s*đầu\s*tư", r"gọi\s*vốn",
    r"mô\s*hình\s*kinh\s*doanh", r"MVP",
    # English
    r"entrepreneurship", r"startup", r"founder", r"co-founder",
    r"business\s*plan", r"business\s*model", r"lean\s*startup",
    r"MVP", r"minimum\s*viable\s*product", r"pivot",
    r"venture\s*capital", r"angel\s*investor", r"seed\s*funding",
    r"Series\s*A", r"Series\s*B", r"IPO",
    r"valuation", r"equity", r"cap\s*table",
]

# === ETHICS PATTERNS ===
ETHICS_PATTERNS = [
    # Vietnamese
    r"đạo\s*đức", r"trách\s*nhiệm\s*xã\s*hội", r"bền\s*vững",
    r"công\s*bằng", r"minh\s*bạch", r"liêm\s*chính",
    # English
    r"ethics", r"professional\s*ethics", r"code\s*of\s*conduct",
    r"social\s*responsibility", r"CSR", r"sustainability",
    r"fairness", r"transparency", r"integrity", r"accountability",
    r"privacy", r"data\s*protection", r"GDPR",
    r"AI\s*ethics", r"bias", r"discrimination",
]

# === NEW CONTRADICTION PAIRS ===
DATA_STRUCTURES_CONTRADICTIONS = [
    ("stack", "queue"),
    ("queue", "stack"),
    ("LIFO", "FIFO"),
    ("FIFO", "LIFO"),
    ("mảng", "danh sách liên kết"),
    ("array", "linked list"),
    ("O(1)", "O(n)"),
    ("O(n)", "O(1)"),
    ("nhanh", "chậm"),
    ("fast", "slow"),
]

TESTING_CONTRADICTIONS = [
    ("passed", "failed"),
    ("failed", "passed"),
    ("đạt", "không đạt"),
    ("không đạt", "đạt"),
    ("bug", "feature"),
    ("feature", "bug"),
]

BLOCKCHAIN_CONTRADICTIONS = [
    ("centralized", "decentralized"),
    ("decentralized", "centralized"),
    ("tập trung", "phi tập trung"),
    ("phi tập trung", "tập trung"),
    ("proof of work", "proof of stake"),
    ("proof of stake", "proof of work"),
]


def get_all_extended_patterns():
    """Return all extended patterns."""
    all_extended = []
    all_extended.extend(EXTENDED_IT_PATTERNS)
    all_extended.extend(EXTENDED_SCIENCE_PATTERNS)
    all_extended.extend(EXTENDED_BUSINESS_PATTERNS)
    all_extended.extend(EXTENDED_HUMANITIES_PATTERNS)
    return all_extended


def get_all_patterns():
    """Return all patterns combined into a single list (including extended)."""
    all_patterns = []
    all_patterns.extend(GENERAL_PATTERNS)
    # NEW: University General Education
    all_patterns.extend(PHILOSOPHY_ML_PATTERNS)
    all_patterns.extend(HCM_THOUGHT_PATTERNS)
    all_patterns.extend(POLITICAL_ECONOMY_PATTERNS)
    all_patterns.extend(SCIENTIFIC_SOCIALISM_PATTERNS)
    all_patterns.extend(GENERAL_LAW_PATTERNS)
    all_patterns.extend(SQL_PATTERNS)
    all_patterns.extend(SE_CORE_PATTERNS)
    all_patterns.extend(MATH_UNIVERSITY_PATTERNS)
    # Original patterns
    all_patterns.extend(IT_PROGRAMMING_PATTERNS)
    all_patterns.extend(IT_DATABASE_PATTERNS)
    all_patterns.extend(IT_NETWORKING_PATTERNS)
    all_patterns.extend(IT_SECURITY_PATTERNS)
    all_patterns.extend(IT_WEB_SOFTWARE_PATTERNS)
    all_patterns.extend(IT_AI_ML_PATTERNS)
    all_patterns.extend(MATH_PATTERNS)
    all_patterns.extend(PHYSICS_PATTERNS)
    all_patterns.extend(CHEMISTRY_PATTERNS)
    all_patterns.extend(BIOLOGY_PATTERNS)
    all_patterns.extend(HISTORY_GEOGRAPHY_PATTERNS)
    all_patterns.extend(PHILOSOPHY_REASONING_PATTERNS)
    all_patterns.extend(ECONOMICS_BUSINESS_PATTERNS)
    all_patterns.extend(LAW_PATTERNS)
    all_patterns.extend(LINGUISTICS_PATTERNS)
    # Additional patterns
    all_patterns.extend(LITERATURE_PATTERNS)
    all_patterns.extend(PSYCHOLOGY_PATTERNS)
    all_patterns.extend(MEDICINE_PATTERNS)
    all_patterns.extend(ARCHITECTURE_PATTERNS)
    all_patterns.extend(MUSIC_ART_PATTERNS)
    # University-level patterns
    all_patterns.extend(ACCOUNTING_PATTERNS)
    all_patterns.extend(STATISTICS_PATTERNS)
    all_patterns.extend(MARKETING_PATTERNS)
    all_patterns.extend(SOCIOLOGY_PATTERNS)
    all_patterns.extend(ENVIRONMENTAL_PATTERNS)
    # Data Science & Engineering patterns
    all_patterns.extend(DATA_STRUCTURES_PATTERNS)
    all_patterns.extend(ALGORITHMS_PATTERNS)
    all_patterns.extend(MOBILE_DEV_PATTERNS)
    all_patterns.extend(DEVOPS_PATTERNS)
    all_patterns.extend(TESTING_PATTERNS)
    all_patterns.extend(UX_UI_PATTERNS)
    all_patterns.extend(PROJECT_MGMT_PATTERNS)
    all_patterns.extend(BLOCKCHAIN_PATTERNS)
    # Business & Soft Skills patterns
    all_patterns.extend(HR_PATTERNS)
    all_patterns.extend(COMMUNICATION_PATTERNS)
    all_patterns.extend(ENTREPRENEURSHIP_PATTERNS)
    all_patterns.extend(ETHICS_PATTERNS)
    # Include extended patterns
    all_patterns.extend(get_all_extended_patterns())
    return all_patterns


def get_all_contradiction_pairs():
    """Return all contradiction pairs combined into a single list."""
    all_contradictions = []
    all_contradictions.extend(IT_CONTRADICTIONS)
    all_contradictions.extend(EDUCATION_CONTRADICTIONS)
    all_contradictions.extend(PHILOSOPHY_CONTRADICTIONS)
    all_contradictions.extend(POLITICS_HISTORY_CONTRADICTIONS)
    all_contradictions.extend(ECONOMICS_CONTRADICTIONS)
    all_contradictions.extend(SCIENCE_CONTRADICTIONS)
    all_contradictions.extend(MATH_CONTRADICTIONS)
    all_contradictions.extend(GENERAL_CONTRADICTIONS)
    # Additional contradictions
    all_contradictions.extend(LITERATURE_CONTRADICTIONS)
    all_contradictions.extend(PSYCHOLOGY_CONTRADICTIONS)
    all_contradictions.extend(MEDICINE_CONTRADICTIONS)
    all_contradictions.extend(ARCHITECTURE_CONTRADICTIONS)
    all_contradictions.extend(MUSIC_ART_CONTRADICTIONS)
    # University-level contradictions
    all_contradictions.extend(ACCOUNTING_CONTRADICTIONS)
    all_contradictions.extend(STATISTICS_CONTRADICTIONS)
    all_contradictions.extend(ENVIRONMENTAL_CONTRADICTIONS)
    # New contradictions
    all_contradictions.extend(DATA_STRUCTURES_CONTRADICTIONS)
    all_contradictions.extend(TESTING_CONTRADICTIONS)
    all_contradictions.extend(BLOCKCHAIN_CONTRADICTIONS)
    return all_contradictions


def get_contradiction_dict():
    # Return contradictions as a dictionary for fast lookup
    contradiction_dict = {}
    for word1, word2 in get_all_contradiction_pairs():
        if word1 not in contradiction_dict:
            contradiction_dict[word1] = set()
        contradiction_dict[word1].add(word2)
    return contradiction_dict


def get_contradictions_by_category(category: str):
    # Return contradiction pairs for a specific category
    categories = {
        "it": IT_CONTRADICTIONS,
        "education": EDUCATION_CONTRADICTIONS,
        "philosophy": PHILOSOPHY_CONTRADICTIONS,
        "politics": POLITICS_HISTORY_CONTRADICTIONS,
        "economics": ECONOMICS_CONTRADICTIONS,
        "science": SCIENCE_CONTRADICTIONS,
        "math": MATH_CONTRADICTIONS,
        "general": GENERAL_CONTRADICTIONS,
    }
    return categories.get(category.lower(), [])

