import React, { createContext, useContext, useState, useEffect } from 'react';

// Translations
const translations = {
    vi: {
        // Common
        save: 'Lưu',
        cancel: 'Hủy',
        delete: 'Xóa',
        edit: 'Chỉnh sửa',
        view: 'Xem',
        search: 'Tìm kiếm',
        loading: 'Đang tải...',
        noData: 'Không có dữ liệu',
        confirm: 'Xác nhận',
        success: 'Thành công',
        error: 'Lỗi',

        // Sidebar
        dashboard: 'Dashboard',
        userManagement: 'Quản lý người dùng',
        examManagement: 'Quản lý bài thi',
        examOverview: 'Tổng quan bài thi',
        results: 'Kết quả',
        systemLogs: 'System Logs',
        settings: 'Cài đặt',
        adminPanel: 'Admin Panel',
        logout: 'Đăng xuất',

        // Dashboard
        totalStudents: 'Tổng số sinh viên',
        totalInstructors: 'Tổng số giảng viên',
        totalExams: 'Tổng bài thi đã tải lên',
        totalRooms: 'Tổng số phòng thi',
        publishedRooms: 'Phòng thi đã công bố',
        upcomingExams: 'Bài thi sắp diễn ra',
        viewAllExams: 'Xem tất cả bài thi',
        userGrowth: 'Thống kê tăng trưởng người dùng',
        last12Months: '12 tháng gần đây',
        performance: 'Hiệu suất',
        sinceLastMonth: 'so với tháng trước',

        // User Management
        editUser: 'Chỉnh sửa người dùng',
        userDetails: 'Chi tiết người dùng',
        confirmDelete: 'Xác nhận xóa',
        deleteConfirmText: 'Bạn có chắc chắn muốn xóa?',
        cannotUndo: 'Hành động này không thể hoàn tác.',
        fullName: 'Họ và tên',
        email: 'Email',
        role: 'Vai trò',
        gender: 'Giới tính',
        phone: 'Số điện thoại',
        address: 'Địa chỉ',
        createdAt: 'Ngày tạo',
        notUpdated: 'Chưa cập nhật',
        allRoles: 'Tất cả vai trò',
        searchByNameOrEmail: 'Tìm kiếm theo tên hoặc email...',
        showing: 'Hiển thị',
        of: 'trong tổng số',
        users: 'người dùng',
        page: 'Trang',
        saveChanges: 'Lưu thay đổi',
        saving: 'Đang lưu...',
        deleting: 'Đang xóa...',
        cannotChangeAdminRole: 'Không thể thay đổi role của Admin',
        cannotDeleteAdmin: 'Không thể xóa Admin',
        male: 'Nam',
        female: 'Nữ',
        other: 'Khác',
        notSelected: 'Chưa chọn',

        // Exam Management
        instructor: 'Giảng viên',
        status: 'Trạng thái',
        timeOpen: 'Thời gian mở',
        timeClose: 'Thời gian đóng',
        duration: 'Thời lượng',
        minutes: 'phút',
        questions: 'câu hỏi',
        candidates: 'Thí sinh',
        allStatus: 'Tất cả trạng thái',
        searchExam: 'Tìm kiếm bài thi...',
        ongoing: 'Đang diễn ra',
        upcoming: 'Sắp diễn ra',
        ended: 'Đã kết thúc',
        draft: 'Bản nháp',
        updateEndTime: 'Cập nhật thời gian kết thúc',
        newEndTime: 'Thời gian kết thúc mới',
        endTimeNote: '* Thời gian kết thúc phải sau thời điểm hiện tại',
        cannotDeleteOngoing: 'Không thể xóa bài thi đang diễn ra',
        examDetails: 'Chi tiết bài thi',
        questionList: 'Danh sách câu hỏi',

        // Results
        student: 'Sinh viên',
        exam: 'Bài thi',
        score: 'Điểm',
        aiScore: 'AI Score',
        submittedAt: 'Nộp lúc',
        allExams: 'Tất cả bài thi',
        totalResults: 'Tổng kết quả',
        confirmed: 'Đã xác nhận',
        pending: 'Chờ chấm',
        avgScore: 'Điểm TB',
        editScore: 'Sửa điểm',
        currentScore: 'Điểm hiện tại',
        newScore: 'Điểm mới',
        exams: 'bài thi',
        resultsText: 'kết quả',

        // System Logs
        activityLogs: 'Activity Logs',
        suspiciousActivities: 'Suspicious Activities',
        time: 'Thời gian',
        admin: 'Admin',
        action: 'Hành động',
        table: 'Bảng',
        description: 'Mô tả',
        ip: 'IP',
        allActions: 'Tất cả hành động',
        searchLogs: 'Tìm kiếm theo email hoặc mô tả...',
        refresh: 'Làm mới',
        login: 'Đăng nhập',
        create: 'Tạo mới',
        update: 'Cập nhật',
        backup: 'Backup',
        restore: 'Restore',
        noSuspicious: 'Không có hoạt động đáng ngờ nào!',
        systemSafe: 'Hệ thống đang hoạt động an toàn',
        markReviewed: 'Đánh dấu đã xem',
        reviewed: 'Đã xem xét',
        logs: 'logs',

        // Settings
        settingsTitle: 'Cài đặt',
        settingsDesc: 'Cấu hình hệ thống và tùy chọn cá nhân',
        appearance: 'Giao diện',
        theme: 'Theme',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        language: 'Ngôn ngữ',
        vietnamese: 'Tiếng Việt',
        english: 'English',
        growthTarget: 'Mục tiêu tăng trưởng',
        yearlyUserTarget: 'Mục tiêu người dùng mới trong năm',
        yearlyUserTargetDesc: 'Số lượng tài khoản mới mong muốn đạt được trong năm nay',
        backupConfig: 'Cấu hình Backup',
        autoBackup: 'Backup tự động',
        backupTime: 'Thời gian backup',
        retentionDays: 'Giữ backup (ngày)',
        createBackupNow: 'Tạo Backup Ngay',
        creatingBackup: 'Đang backup...',
        suspiciousThresholds: 'Ngưỡng phát hiện bất thường',
        massDelete: 'Xóa hàng loạt (số lần/phút)',
        failedLogin: 'Login thất bại (số lần/10 phút)',
        restoreFrequency: 'Restore liên tục (số lần/ngày)',
        recentBackups: 'Lịch sử Backup gần đây',
        noBackups: 'Chưa có backup nào',
        backupType: 'Loại',
        fileName: 'File',
        fileSize: 'Kích thước',
        performedBy: 'Thực hiện bởi',
        manual: 'Thủ công',
        scheduled: 'Tự động',
        completed: 'Hoàn thành',
        failed: 'Thất bại',
        saveSettings: 'Lưu cài đặt',
        savingSettings: 'Đang lưu...',
        updateSuccess: 'Cập nhật thành công!',
        backupSuccess: 'Backup thành công!',

        // Exam Overview
        examOverviewTitle: 'Tổng quan bài thi',
        examOverviewDesc: 'Xem tổng quan các bài thi và câu hỏi',
        totalExamsCount: 'Tổng bài thi',
        ongoingCount: 'Đang diễn ra',
        upcomingCount: 'Sắp diễn ra',
        totalQuestionsCount: 'Tổng câu hỏi',
        viewDetails: 'Xem chi tiết',
        noQuestionsFound: 'Không có câu hỏi nào',
        loadingQuestions: 'Đang tải câu hỏi...',
        points: 'điểm'
    },
    en: {
        // Common
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        view: 'View',
        search: 'Search',
        loading: 'Loading...',
        noData: 'No data',
        confirm: 'Confirm',
        success: 'Success',
        error: 'Error',

        // Sidebar
        dashboard: 'Dashboard',
        userManagement: 'User Management',
        examManagement: 'Exam Management',
        examOverview: 'Exam Overview',
        results: 'Results',
        systemLogs: 'System Logs',
        settings: 'Settings',
        adminPanel: 'Admin Panel',
        logout: 'Logout',

        // Dashboard
        totalStudents: 'Total Students',
        totalInstructors: 'Total Instructors',
        totalExams: 'Total Exams Uploaded',
        totalRooms: 'Total Rooms',
        publishedRooms: 'Published Rooms',
        upcomingExams: 'Upcoming Exams',
        viewAllExams: 'View All Exams',
        userGrowth: 'User Growth Statistics',
        last12Months: 'Last 12 Months',
        performance: 'Performance',
        sinceLastMonth: 'since last month',

        // User Management
        editUser: 'Edit User',
        userDetails: 'User Details',
        confirmDelete: 'Confirm Delete',
        deleteConfirmText: 'Are you sure you want to delete?',
        cannotUndo: 'This action cannot be undone.',
        fullName: 'Full Name',
        email: 'Email',
        role: 'Role',
        gender: 'Gender',
        phone: 'Phone',
        address: 'Address',
        createdAt: 'Created At',
        notUpdated: 'Not updated',
        allRoles: 'All Roles',
        searchByNameOrEmail: 'Search by name or email...',
        showing: 'Showing',
        of: 'of',
        users: 'users',
        page: 'Page',
        saveChanges: 'Save Changes',
        saving: 'Saving...',
        deleting: 'Deleting...',
        cannotChangeAdminRole: 'Cannot change Admin role',
        cannotDeleteAdmin: 'Cannot delete Admin',
        male: 'Male',
        female: 'Female',
        other: 'Other',
        notSelected: 'Not selected',

        // Exam Management
        instructor: 'Instructor',
        status: 'Status',
        timeOpen: 'Open Time',
        timeClose: 'Close Time',
        duration: 'Duration',
        minutes: 'minutes',
        questions: 'questions',
        candidates: 'Candidates',
        allStatus: 'All Status',
        searchExam: 'Search exam...',
        ongoing: 'Ongoing',
        upcoming: 'Upcoming',
        ended: 'Ended',
        draft: 'Draft',
        updateEndTime: 'Update End Time',
        newEndTime: 'New End Time',
        endTimeNote: '* End time must be after current time',
        cannotDeleteOngoing: 'Cannot delete ongoing exam',
        examDetails: 'Exam Details',
        questionList: 'Question List',

        // Results
        student: 'Student',
        exam: 'Exam',
        score: 'Score',
        aiScore: 'AI Score',
        submittedAt: 'Submitted At',
        allExams: 'All Exams',
        totalResults: 'Total Results',
        confirmed: 'Confirmed',
        pending: 'Pending',
        avgScore: 'Avg Score',
        editScore: 'Edit Score',
        currentScore: 'Current Score',
        newScore: 'New Score',
        exams: 'exams',
        resultsText: 'results',

        // System Logs
        activityLogs: 'Activity Logs',
        suspiciousActivities: 'Suspicious Activities',
        time: 'Time',
        admin: 'Admin',
        action: 'Action',
        table: 'Table',
        description: 'Description',
        ip: 'IP',
        allActions: 'All Actions',
        searchLogs: 'Search by email or description...',
        refresh: 'Refresh',
        login: 'Login',
        create: 'Create',
        update: 'Update',
        backup: 'Backup',
        restore: 'Restore',
        noSuspicious: 'No suspicious activities!',
        systemSafe: 'System is running safely',
        markReviewed: 'Mark as reviewed',
        reviewed: 'Reviewed',
        logs: 'logs',

        // Settings
        settingsTitle: 'Settings',
        settingsDesc: 'System configuration and personal preferences',
        appearance: 'Appearance',
        theme: 'Theme',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        language: 'Language',
        vietnamese: 'Vietnamese',
        english: 'English',
        growthTarget: 'Growth Target',
        yearlyUserTarget: 'Yearly user target',
        yearlyUserTargetDesc: 'Number of new accounts to achieve this year',
        backupConfig: 'Backup Configuration',
        autoBackup: 'Auto Backup',
        backupTime: 'Backup Time',
        retentionDays: 'Retention (days)',
        createBackupNow: 'Create Backup Now',
        creatingBackup: 'Creating backup...',
        suspiciousThresholds: 'Suspicious Detection Thresholds',
        massDelete: 'Mass delete (times/minute)',
        failedLogin: 'Failed login (times/10 minutes)',
        restoreFrequency: 'Restore frequency (times/day)',
        recentBackups: 'Recent Backups',
        noBackups: 'No backups yet',
        backupType: 'Type',
        fileName: 'File',
        fileSize: 'Size',
        performedBy: 'Performed By',
        manual: 'Manual',
        scheduled: 'Scheduled',
        completed: 'Completed',
        failed: 'Failed',
        saveSettings: 'Save Settings',
        savingSettings: 'Saving...',
        updateSuccess: 'Updated successfully!',
        backupSuccess: 'Backup successful!',

        // Exam Overview
        examOverviewTitle: 'Exam Overview',
        examOverviewDesc: 'View exam overview and questions',
        totalExamsCount: 'Total Exams',
        ongoingCount: 'Ongoing',
        upcomingCount: 'Upcoming',
        totalQuestionsCount: 'Total Questions',
        viewDetails: 'View Details',
        noQuestionsFound: 'No questions found',
        loadingQuestions: 'Loading questions...',
        points: 'points'
    }
};

const LanguageContext = createContext();

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('admin_language') || 'vi';
    });

    const t = (key) => {
        return translations[language]?.[key] || translations['vi']?.[key] || key;
    };

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('admin_language', lang);
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export default LanguageContext;
